// Code generated by internal/generator. DO NOT EDIT.
//
// Edit internal/generator/templates/gen_visitor_test.go.tmpl instead,
// then run: go generate ./...

package parser

import (
	"reflect"
	"testing"
)

// TestVisitorCoversAllNodes checks that the Visitor interface declares a visit
// method for every node type, and that DefaultVisitor implements all of them.
// A node added upstream therefore cannot land without visitor support.
func TestVisitorCoversAllNodes(t *testing.T) {
	visitorType := reflect.TypeOf((*Visitor)(nil)).Elem()
	defaultVisitor := reflect.TypeOf((*DefaultVisitor)(nil))

	cases := []string{
		"VisitAliasGlobalVariableNode",
		"VisitAliasMethodNode",
		"VisitAlternationPatternNode",
		"VisitAndNode",
		"VisitArgumentsNode",
		"VisitArrayNode",
		"VisitArrayPatternNode",
		"VisitAssocNode",
		"VisitAssocSplatNode",
		"VisitBackReferenceReadNode",
		"VisitBeginNode",
		"VisitBlockArgumentNode",
		"VisitBlockLocalVariableNode",
		"VisitBlockNode",
		"VisitBlockParameterNode",
		"VisitBlockParametersNode",
		"VisitBreakNode",
		"VisitCallAndWriteNode",
		"VisitCallNode",
		"VisitCallOperatorWriteNode",
		"VisitCallOrWriteNode",
		"VisitCallTargetNode",
		"VisitCapturePatternNode",
		"VisitCaseMatchNode",
		"VisitCaseNode",
		"VisitClassNode",
		"VisitClassVariableAndWriteNode",
		"VisitClassVariableOperatorWriteNode",
		"VisitClassVariableOrWriteNode",
		"VisitClassVariableReadNode",
		"VisitClassVariableTargetNode",
		"VisitClassVariableWriteNode",
		"VisitConstantAndWriteNode",
		"VisitConstantOperatorWriteNode",
		"VisitConstantOrWriteNode",
		"VisitConstantPathAndWriteNode",
		"VisitConstantPathNode",
		"VisitConstantPathOperatorWriteNode",
		"VisitConstantPathOrWriteNode",
		"VisitConstantPathTargetNode",
		"VisitConstantPathWriteNode",
		"VisitConstantReadNode",
		"VisitConstantTargetNode",
		"VisitConstantWriteNode",
		"VisitDefNode",
		"VisitDefinedNode",
		"VisitElseNode",
		"VisitEmbeddedStatementsNode",
		"VisitEmbeddedVariableNode",
		"VisitEnsureNode",
		"VisitFalseNode",
		"VisitFindPatternNode",
		"VisitFlipFlopNode",
		"VisitFloatNode",
		"VisitForNode",
		"VisitForwardingArgumentsNode",
		"VisitForwardingParameterNode",
		"VisitForwardingSuperNode",
		"VisitGlobalVariableAndWriteNode",
		"VisitGlobalVariableOperatorWriteNode",
		"VisitGlobalVariableOrWriteNode",
		"VisitGlobalVariableReadNode",
		"VisitGlobalVariableTargetNode",
		"VisitGlobalVariableWriteNode",
		"VisitHashNode",
		"VisitHashPatternNode",
		"VisitIfNode",
		"VisitImaginaryNode",
		"VisitImplicitNode",
		"VisitImplicitRestNode",
		"VisitInNode",
		"VisitIndexAndWriteNode",
		"VisitIndexOperatorWriteNode",
		"VisitIndexOrWriteNode",
		"VisitIndexTargetNode",
		"VisitInstanceVariableAndWriteNode",
		"VisitInstanceVariableOperatorWriteNode",
		"VisitInstanceVariableOrWriteNode",
		"VisitInstanceVariableReadNode",
		"VisitInstanceVariableTargetNode",
		"VisitInstanceVariableWriteNode",
		"VisitIntegerNode",
		"VisitInterpolatedMatchLastLineNode",
		"VisitInterpolatedRegularExpressionNode",
		"VisitInterpolatedStringNode",
		"VisitInterpolatedSymbolNode",
		"VisitInterpolatedXStringNode",
		"VisitItLocalVariableReadNode",
		"VisitItParametersNode",
		"VisitKeywordHashNode",
		"VisitKeywordRestParameterNode",
		"VisitLambdaNode",
		"VisitLocalVariableAndWriteNode",
		"VisitLocalVariableOperatorWriteNode",
		"VisitLocalVariableOrWriteNode",
		"VisitLocalVariableReadNode",
		"VisitLocalVariableTargetNode",
		"VisitLocalVariableWriteNode",
		"VisitMatchLastLineNode",
		"VisitMatchPredicateNode",
		"VisitMatchRequiredNode",
		"VisitMatchWriteNode",
		"VisitMissingNode",
		"VisitModuleNode",
		"VisitMultiTargetNode",
		"VisitMultiWriteNode",
		"VisitNextNode",
		"VisitNilNode",
		"VisitNoKeywordsParameterNode",
		"VisitNumberedParametersNode",
		"VisitNumberedReferenceReadNode",
		"VisitOptionalKeywordParameterNode",
		"VisitOptionalParameterNode",
		"VisitOrNode",
		"VisitParametersNode",
		"VisitParenthesesNode",
		"VisitPinnedExpressionNode",
		"VisitPinnedVariableNode",
		"VisitPostExecutionNode",
		"VisitPreExecutionNode",
		"VisitProgramNode",
		"VisitRangeNode",
		"VisitRationalNode",
		"VisitRedoNode",
		"VisitRegularExpressionNode",
		"VisitRequiredKeywordParameterNode",
		"VisitRequiredParameterNode",
		"VisitRescueModifierNode",
		"VisitRescueNode",
		"VisitRestParameterNode",
		"VisitRetryNode",
		"VisitReturnNode",
		"VisitSelfNode",
		"VisitShareableConstantNode",
		"VisitSingletonClassNode",
		"VisitSourceEncodingNode",
		"VisitSourceFileNode",
		"VisitSourceLineNode",
		"VisitSplatNode",
		"VisitStatementsNode",
		"VisitStringNode",
		"VisitSuperNode",
		"VisitSymbolNode",
		"VisitTrueNode",
		"VisitUndefNode",
		"VisitUnlessNode",
		"VisitUntilNode",
		"VisitWhenNode",
		"VisitWhileNode",
		"VisitXStringNode",
		"VisitYieldNode",
	}

	for _, name := range cases {
		method, ok := visitorType.MethodByName(name)
		if !ok {
			t.Errorf("Visitor is missing %s", name)
			continue
		}

		if got := method.Type.NumIn(); got != 1 {
			t.Errorf("Visitor.%s takes %d arguments, want 1", name, got)
		}

		if _, ok := defaultVisitor.MethodByName(name); !ok {
			t.Errorf("DefaultVisitor is missing %s", name)
		}
	}

	// Guard against the interface drifting ahead of the node list: the
	// visit methods plus the three BasicVisitor methods must account for
	// the whole interface.
	if got, want := visitorType.NumMethod(), len(cases)+3; got != want {
		t.Errorf("Visitor declares %d methods, want %d", got, want)
	}
}

// TestChildNodesMatchConfig checks that ChildNodes reports exactly the fields
// config.yml marks as child nodes, in declaration order. It builds each node
// with zero values, so only the node-typed fields that are non-nil appear.
func TestChildNodesMatchConfig(t *testing.T) {
	cases := []struct {
		name string
		node Node
		// want is the number of child slots that are non-nil for a node
		// whose fields are all zero valued. Required node fields are nil
		// interfaces at that point, so they still count as present.
		wantChildFields []string
	}{
		{
			"AliasGlobalVariableNode",
			&AliasGlobalVariableNode{},
			[]string{
				"NewName",
				"OldName",
			},
		},
		{
			"AliasMethodNode",
			&AliasMethodNode{},
			[]string{
				"NewName",
				"OldName",
			},
		},
		{
			"AlternationPatternNode",
			&AlternationPatternNode{},
			[]string{
				"Left",
				"Right",
			},
		},
		{
			"AndNode",
			&AndNode{},
			[]string{
				"Left",
				"Right",
			},
		},
		{
			"ArgumentsNode",
			&ArgumentsNode{},
			[]string{},
		},
		{
			"ArrayNode",
			&ArrayNode{},
			[]string{},
		},
		{
			"ArrayPatternNode",
			&ArrayPatternNode{},
			[]string{},
		},
		{
			"AssocNode",
			&AssocNode{},
			[]string{
				"Key",
				"Value",
			},
		},
		{
			"AssocSplatNode",
			&AssocSplatNode{},
			[]string{},
		},
		{
			"BackReferenceReadNode",
			&BackReferenceReadNode{},
			[]string{},
		},
		{
			"BeginNode",
			&BeginNode{},
			[]string{},
		},
		{
			"BlockArgumentNode",
			&BlockArgumentNode{},
			[]string{},
		},
		{
			"BlockLocalVariableNode",
			&BlockLocalVariableNode{},
			[]string{},
		},
		{
			"BlockNode",
			&BlockNode{},
			[]string{},
		},
		{
			"BlockParameterNode",
			&BlockParameterNode{},
			[]string{},
		},
		{
			"BlockParametersNode",
			&BlockParametersNode{},
			[]string{},
		},
		{
			"BreakNode",
			&BreakNode{},
			[]string{},
		},
		{
			"CallAndWriteNode",
			&CallAndWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"CallNode",
			&CallNode{},
			[]string{},
		},
		{
			"CallOperatorWriteNode",
			&CallOperatorWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"CallOrWriteNode",
			&CallOrWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"CallTargetNode",
			&CallTargetNode{},
			[]string{
				"Receiver",
			},
		},
		{
			"CapturePatternNode",
			&CapturePatternNode{},
			[]string{
				"Value",
				"Target",
			},
		},
		{
			"CaseMatchNode",
			&CaseMatchNode{},
			[]string{},
		},
		{
			"CaseNode",
			&CaseNode{},
			[]string{},
		},
		{
			"ClassNode",
			&ClassNode{},
			[]string{
				"ConstantPath",
			},
		},
		{
			"ClassVariableAndWriteNode",
			&ClassVariableAndWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"ClassVariableOperatorWriteNode",
			&ClassVariableOperatorWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"ClassVariableOrWriteNode",
			&ClassVariableOrWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"ClassVariableReadNode",
			&ClassVariableReadNode{},
			[]string{},
		},
		{
			"ClassVariableTargetNode",
			&ClassVariableTargetNode{},
			[]string{},
		},
		{
			"ClassVariableWriteNode",
			&ClassVariableWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"ConstantAndWriteNode",
			&ConstantAndWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"ConstantOperatorWriteNode",
			&ConstantOperatorWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"ConstantOrWriteNode",
			&ConstantOrWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"ConstantPathAndWriteNode",
			&ConstantPathAndWriteNode{},
			[]string{
				"Target",
				"Value",
			},
		},
		{
			"ConstantPathNode",
			&ConstantPathNode{},
			[]string{},
		},
		{
			"ConstantPathOperatorWriteNode",
			&ConstantPathOperatorWriteNode{},
			[]string{
				"Target",
				"Value",
			},
		},
		{
			"ConstantPathOrWriteNode",
			&ConstantPathOrWriteNode{},
			[]string{
				"Target",
				"Value",
			},
		},
		{
			"ConstantPathTargetNode",
			&ConstantPathTargetNode{},
			[]string{},
		},
		{
			"ConstantPathWriteNode",
			&ConstantPathWriteNode{},
			[]string{
				"Target",
				"Value",
			},
		},
		{
			"ConstantReadNode",
			&ConstantReadNode{},
			[]string{},
		},
		{
			"ConstantTargetNode",
			&ConstantTargetNode{},
			[]string{},
		},
		{
			"ConstantWriteNode",
			&ConstantWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"DefNode",
			&DefNode{},
			[]string{},
		},
		{
			"DefinedNode",
			&DefinedNode{},
			[]string{
				"Value",
			},
		},
		{
			"ElseNode",
			&ElseNode{},
			[]string{},
		},
		{
			"EmbeddedStatementsNode",
			&EmbeddedStatementsNode{},
			[]string{},
		},
		{
			"EmbeddedVariableNode",
			&EmbeddedVariableNode{},
			[]string{
				"Variable",
			},
		},
		{
			"EnsureNode",
			&EnsureNode{},
			[]string{},
		},
		{
			"FalseNode",
			&FalseNode{},
			[]string{},
		},
		{
			"FindPatternNode",
			&FindPatternNode{},
			[]string{
				"Left",
				"Right",
			},
		},
		{
			"FlipFlopNode",
			&FlipFlopNode{},
			[]string{},
		},
		{
			"FloatNode",
			&FloatNode{},
			[]string{},
		},
		{
			"ForNode",
			&ForNode{},
			[]string{
				"Index",
				"Collection",
			},
		},
		{
			"ForwardingArgumentsNode",
			&ForwardingArgumentsNode{},
			[]string{},
		},
		{
			"ForwardingParameterNode",
			&ForwardingParameterNode{},
			[]string{},
		},
		{
			"ForwardingSuperNode",
			&ForwardingSuperNode{},
			[]string{},
		},
		{
			"GlobalVariableAndWriteNode",
			&GlobalVariableAndWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"GlobalVariableOperatorWriteNode",
			&GlobalVariableOperatorWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"GlobalVariableOrWriteNode",
			&GlobalVariableOrWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"GlobalVariableReadNode",
			&GlobalVariableReadNode{},
			[]string{},
		},
		{
			"GlobalVariableTargetNode",
			&GlobalVariableTargetNode{},
			[]string{},
		},
		{
			"GlobalVariableWriteNode",
			&GlobalVariableWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"HashNode",
			&HashNode{},
			[]string{},
		},
		{
			"HashPatternNode",
			&HashPatternNode{},
			[]string{},
		},
		{
			"IfNode",
			&IfNode{},
			[]string{
				"Predicate",
			},
		},
		{
			"ImaginaryNode",
			&ImaginaryNode{},
			[]string{
				"Numeric",
			},
		},
		{
			"ImplicitNode",
			&ImplicitNode{},
			[]string{
				"Value",
			},
		},
		{
			"ImplicitRestNode",
			&ImplicitRestNode{},
			[]string{},
		},
		{
			"InNode",
			&InNode{},
			[]string{
				"Pattern",
			},
		},
		{
			"IndexAndWriteNode",
			&IndexAndWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"IndexOperatorWriteNode",
			&IndexOperatorWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"IndexOrWriteNode",
			&IndexOrWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"IndexTargetNode",
			&IndexTargetNode{},
			[]string{
				"Receiver",
			},
		},
		{
			"InstanceVariableAndWriteNode",
			&InstanceVariableAndWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"InstanceVariableOperatorWriteNode",
			&InstanceVariableOperatorWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"InstanceVariableOrWriteNode",
			&InstanceVariableOrWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"InstanceVariableReadNode",
			&InstanceVariableReadNode{},
			[]string{},
		},
		{
			"InstanceVariableTargetNode",
			&InstanceVariableTargetNode{},
			[]string{},
		},
		{
			"InstanceVariableWriteNode",
			&InstanceVariableWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"IntegerNode",
			&IntegerNode{},
			[]string{},
		},
		{
			"InterpolatedMatchLastLineNode",
			&InterpolatedMatchLastLineNode{},
			[]string{},
		},
		{
			"InterpolatedRegularExpressionNode",
			&InterpolatedRegularExpressionNode{},
			[]string{},
		},
		{
			"InterpolatedStringNode",
			&InterpolatedStringNode{},
			[]string{},
		},
		{
			"InterpolatedSymbolNode",
			&InterpolatedSymbolNode{},
			[]string{},
		},
		{
			"InterpolatedXStringNode",
			&InterpolatedXStringNode{},
			[]string{},
		},
		{
			"ItLocalVariableReadNode",
			&ItLocalVariableReadNode{},
			[]string{},
		},
		{
			"ItParametersNode",
			&ItParametersNode{},
			[]string{},
		},
		{
			"KeywordHashNode",
			&KeywordHashNode{},
			[]string{},
		},
		{
			"KeywordRestParameterNode",
			&KeywordRestParameterNode{},
			[]string{},
		},
		{
			"LambdaNode",
			&LambdaNode{},
			[]string{},
		},
		{
			"LocalVariableAndWriteNode",
			&LocalVariableAndWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"LocalVariableOperatorWriteNode",
			&LocalVariableOperatorWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"LocalVariableOrWriteNode",
			&LocalVariableOrWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"LocalVariableReadNode",
			&LocalVariableReadNode{},
			[]string{},
		},
		{
			"LocalVariableTargetNode",
			&LocalVariableTargetNode{},
			[]string{},
		},
		{
			"LocalVariableWriteNode",
			&LocalVariableWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"MatchLastLineNode",
			&MatchLastLineNode{},
			[]string{},
		},
		{
			"MatchPredicateNode",
			&MatchPredicateNode{},
			[]string{
				"Value",
				"Pattern",
			},
		},
		{
			"MatchRequiredNode",
			&MatchRequiredNode{},
			[]string{
				"Value",
				"Pattern",
			},
		},
		{
			"MatchWriteNode",
			&MatchWriteNode{},
			[]string{
				"Call",
			},
		},
		{
			"MissingNode",
			&MissingNode{},
			[]string{},
		},
		{
			"ModuleNode",
			&ModuleNode{},
			[]string{
				"ConstantPath",
			},
		},
		{
			"MultiTargetNode",
			&MultiTargetNode{},
			[]string{},
		},
		{
			"MultiWriteNode",
			&MultiWriteNode{},
			[]string{
				"Value",
			},
		},
		{
			"NextNode",
			&NextNode{},
			[]string{},
		},
		{
			"NilNode",
			&NilNode{},
			[]string{},
		},
		{
			"NoKeywordsParameterNode",
			&NoKeywordsParameterNode{},
			[]string{},
		},
		{
			"NumberedParametersNode",
			&NumberedParametersNode{},
			[]string{},
		},
		{
			"NumberedReferenceReadNode",
			&NumberedReferenceReadNode{},
			[]string{},
		},
		{
			"OptionalKeywordParameterNode",
			&OptionalKeywordParameterNode{},
			[]string{
				"Value",
			},
		},
		{
			"OptionalParameterNode",
			&OptionalParameterNode{},
			[]string{
				"Value",
			},
		},
		{
			"OrNode",
			&OrNode{},
			[]string{
				"Left",
				"Right",
			},
		},
		{
			"ParametersNode",
			&ParametersNode{},
			[]string{},
		},
		{
			"ParenthesesNode",
			&ParenthesesNode{},
			[]string{},
		},
		{
			"PinnedExpressionNode",
			&PinnedExpressionNode{},
			[]string{
				"Expression",
			},
		},
		{
			"PinnedVariableNode",
			&PinnedVariableNode{},
			[]string{
				"Variable",
			},
		},
		{
			"PostExecutionNode",
			&PostExecutionNode{},
			[]string{},
		},
		{
			"PreExecutionNode",
			&PreExecutionNode{},
			[]string{},
		},
		{
			"ProgramNode",
			&ProgramNode{},
			[]string{
				"Statements",
			},
		},
		{
			"RangeNode",
			&RangeNode{},
			[]string{},
		},
		{
			"RationalNode",
			&RationalNode{},
			[]string{},
		},
		{
			"RedoNode",
			&RedoNode{},
			[]string{},
		},
		{
			"RegularExpressionNode",
			&RegularExpressionNode{},
			[]string{},
		},
		{
			"RequiredKeywordParameterNode",
			&RequiredKeywordParameterNode{},
			[]string{},
		},
		{
			"RequiredParameterNode",
			&RequiredParameterNode{},
			[]string{},
		},
		{
			"RescueModifierNode",
			&RescueModifierNode{},
			[]string{
				"Expression",
				"RescueExpression",
			},
		},
		{
			"RescueNode",
			&RescueNode{},
			[]string{},
		},
		{
			"RestParameterNode",
			&RestParameterNode{},
			[]string{},
		},
		{
			"RetryNode",
			&RetryNode{},
			[]string{},
		},
		{
			"ReturnNode",
			&ReturnNode{},
			[]string{},
		},
		{
			"SelfNode",
			&SelfNode{},
			[]string{},
		},
		{
			"ShareableConstantNode",
			&ShareableConstantNode{},
			[]string{
				"Write",
			},
		},
		{
			"SingletonClassNode",
			&SingletonClassNode{},
			[]string{
				"Expression",
			},
		},
		{
			"SourceEncodingNode",
			&SourceEncodingNode{},
			[]string{},
		},
		{
			"SourceFileNode",
			&SourceFileNode{},
			[]string{},
		},
		{
			"SourceLineNode",
			&SourceLineNode{},
			[]string{},
		},
		{
			"SplatNode",
			&SplatNode{},
			[]string{},
		},
		{
			"StatementsNode",
			&StatementsNode{},
			[]string{},
		},
		{
			"StringNode",
			&StringNode{},
			[]string{},
		},
		{
			"SuperNode",
			&SuperNode{},
			[]string{},
		},
		{
			"SymbolNode",
			&SymbolNode{},
			[]string{},
		},
		{
			"TrueNode",
			&TrueNode{},
			[]string{},
		},
		{
			"UndefNode",
			&UndefNode{},
			[]string{},
		},
		{
			"UnlessNode",
			&UnlessNode{},
			[]string{
				"Predicate",
			},
		},
		{
			"UntilNode",
			&UntilNode{},
			[]string{
				"Predicate",
			},
		},
		{
			"WhenNode",
			&WhenNode{},
			[]string{},
		},
		{
			"WhileNode",
			&WhileNode{},
			[]string{
				"Predicate",
			},
		},
		{
			"XStringNode",
			&XStringNode{},
			[]string{},
		},
		{
			"YieldNode",
			&YieldNode{},
			[]string{},
		},
	}

	for _, tc := range cases {
		// A zero-valued node has nil optional fields and empty lists, so
		// ChildNodes returns one entry per required node field.
		got := tc.node.ChildNodes()

		if len(got) != len(tc.wantChildFields) {
			t.Errorf("%s: ChildNodes returned %d entries, want %d (%v)",
				tc.name, len(got), len(tc.wantChildFields), tc.wantChildFields)
		}
	}
}

// TestAcceptDispatchesToMatchingMethod checks that each node's Accept calls the
// visit method named after that node, so dispatch cannot be miswired.
func TestAcceptDispatchesToMatchingMethod(t *testing.T) {
	cases := []struct {
		name string
		node Node
	}{
		{"AliasGlobalVariableNode", &AliasGlobalVariableNode{}},
		{"AliasMethodNode", &AliasMethodNode{}},
		{"AlternationPatternNode", &AlternationPatternNode{}},
		{"AndNode", &AndNode{}},
		{"ArgumentsNode", &ArgumentsNode{}},
		{"ArrayNode", &ArrayNode{}},
		{"ArrayPatternNode", &ArrayPatternNode{}},
		{"AssocNode", &AssocNode{}},
		{"AssocSplatNode", &AssocSplatNode{}},
		{"BackReferenceReadNode", &BackReferenceReadNode{}},
		{"BeginNode", &BeginNode{}},
		{"BlockArgumentNode", &BlockArgumentNode{}},
		{"BlockLocalVariableNode", &BlockLocalVariableNode{}},
		{"BlockNode", &BlockNode{}},
		{"BlockParameterNode", &BlockParameterNode{}},
		{"BlockParametersNode", &BlockParametersNode{}},
		{"BreakNode", &BreakNode{}},
		{"CallAndWriteNode", &CallAndWriteNode{}},
		{"CallNode", &CallNode{}},
		{"CallOperatorWriteNode", &CallOperatorWriteNode{}},
		{"CallOrWriteNode", &CallOrWriteNode{}},
		{"CallTargetNode", &CallTargetNode{}},
		{"CapturePatternNode", &CapturePatternNode{}},
		{"CaseMatchNode", &CaseMatchNode{}},
		{"CaseNode", &CaseNode{}},
		{"ClassNode", &ClassNode{}},
		{"ClassVariableAndWriteNode", &ClassVariableAndWriteNode{}},
		{"ClassVariableOperatorWriteNode", &ClassVariableOperatorWriteNode{}},
		{"ClassVariableOrWriteNode", &ClassVariableOrWriteNode{}},
		{"ClassVariableReadNode", &ClassVariableReadNode{}},
		{"ClassVariableTargetNode", &ClassVariableTargetNode{}},
		{"ClassVariableWriteNode", &ClassVariableWriteNode{}},
		{"ConstantAndWriteNode", &ConstantAndWriteNode{}},
		{"ConstantOperatorWriteNode", &ConstantOperatorWriteNode{}},
		{"ConstantOrWriteNode", &ConstantOrWriteNode{}},
		{"ConstantPathAndWriteNode", &ConstantPathAndWriteNode{}},
		{"ConstantPathNode", &ConstantPathNode{}},
		{"ConstantPathOperatorWriteNode", &ConstantPathOperatorWriteNode{}},
		{"ConstantPathOrWriteNode", &ConstantPathOrWriteNode{}},
		{"ConstantPathTargetNode", &ConstantPathTargetNode{}},
		{"ConstantPathWriteNode", &ConstantPathWriteNode{}},
		{"ConstantReadNode", &ConstantReadNode{}},
		{"ConstantTargetNode", &ConstantTargetNode{}},
		{"ConstantWriteNode", &ConstantWriteNode{}},
		{"DefNode", &DefNode{}},
		{"DefinedNode", &DefinedNode{}},
		{"ElseNode", &ElseNode{}},
		{"EmbeddedStatementsNode", &EmbeddedStatementsNode{}},
		{"EmbeddedVariableNode", &EmbeddedVariableNode{}},
		{"EnsureNode", &EnsureNode{}},
		{"FalseNode", &FalseNode{}},
		{"FindPatternNode", &FindPatternNode{}},
		{"FlipFlopNode", &FlipFlopNode{}},
		{"FloatNode", &FloatNode{}},
		{"ForNode", &ForNode{}},
		{"ForwardingArgumentsNode", &ForwardingArgumentsNode{}},
		{"ForwardingParameterNode", &ForwardingParameterNode{}},
		{"ForwardingSuperNode", &ForwardingSuperNode{}},
		{"GlobalVariableAndWriteNode", &GlobalVariableAndWriteNode{}},
		{"GlobalVariableOperatorWriteNode", &GlobalVariableOperatorWriteNode{}},
		{"GlobalVariableOrWriteNode", &GlobalVariableOrWriteNode{}},
		{"GlobalVariableReadNode", &GlobalVariableReadNode{}},
		{"GlobalVariableTargetNode", &GlobalVariableTargetNode{}},
		{"GlobalVariableWriteNode", &GlobalVariableWriteNode{}},
		{"HashNode", &HashNode{}},
		{"HashPatternNode", &HashPatternNode{}},
		{"IfNode", &IfNode{}},
		{"ImaginaryNode", &ImaginaryNode{}},
		{"ImplicitNode", &ImplicitNode{}},
		{"ImplicitRestNode", &ImplicitRestNode{}},
		{"InNode", &InNode{}},
		{"IndexAndWriteNode", &IndexAndWriteNode{}},
		{"IndexOperatorWriteNode", &IndexOperatorWriteNode{}},
		{"IndexOrWriteNode", &IndexOrWriteNode{}},
		{"IndexTargetNode", &IndexTargetNode{}},
		{"InstanceVariableAndWriteNode", &InstanceVariableAndWriteNode{}},
		{"InstanceVariableOperatorWriteNode", &InstanceVariableOperatorWriteNode{}},
		{"InstanceVariableOrWriteNode", &InstanceVariableOrWriteNode{}},
		{"InstanceVariableReadNode", &InstanceVariableReadNode{}},
		{"InstanceVariableTargetNode", &InstanceVariableTargetNode{}},
		{"InstanceVariableWriteNode", &InstanceVariableWriteNode{}},
		{"IntegerNode", &IntegerNode{}},
		{"InterpolatedMatchLastLineNode", &InterpolatedMatchLastLineNode{}},
		{"InterpolatedRegularExpressionNode", &InterpolatedRegularExpressionNode{}},
		{"InterpolatedStringNode", &InterpolatedStringNode{}},
		{"InterpolatedSymbolNode", &InterpolatedSymbolNode{}},
		{"InterpolatedXStringNode", &InterpolatedXStringNode{}},
		{"ItLocalVariableReadNode", &ItLocalVariableReadNode{}},
		{"ItParametersNode", &ItParametersNode{}},
		{"KeywordHashNode", &KeywordHashNode{}},
		{"KeywordRestParameterNode", &KeywordRestParameterNode{}},
		{"LambdaNode", &LambdaNode{}},
		{"LocalVariableAndWriteNode", &LocalVariableAndWriteNode{}},
		{"LocalVariableOperatorWriteNode", &LocalVariableOperatorWriteNode{}},
		{"LocalVariableOrWriteNode", &LocalVariableOrWriteNode{}},
		{"LocalVariableReadNode", &LocalVariableReadNode{}},
		{"LocalVariableTargetNode", &LocalVariableTargetNode{}},
		{"LocalVariableWriteNode", &LocalVariableWriteNode{}},
		{"MatchLastLineNode", &MatchLastLineNode{}},
		{"MatchPredicateNode", &MatchPredicateNode{}},
		{"MatchRequiredNode", &MatchRequiredNode{}},
		{"MatchWriteNode", &MatchWriteNode{}},
		{"MissingNode", &MissingNode{}},
		{"ModuleNode", &ModuleNode{}},
		{"MultiTargetNode", &MultiTargetNode{}},
		{"MultiWriteNode", &MultiWriteNode{}},
		{"NextNode", &NextNode{}},
		{"NilNode", &NilNode{}},
		{"NoKeywordsParameterNode", &NoKeywordsParameterNode{}},
		{"NumberedParametersNode", &NumberedParametersNode{}},
		{"NumberedReferenceReadNode", &NumberedReferenceReadNode{}},
		{"OptionalKeywordParameterNode", &OptionalKeywordParameterNode{}},
		{"OptionalParameterNode", &OptionalParameterNode{}},
		{"OrNode", &OrNode{}},
		{"ParametersNode", &ParametersNode{}},
		{"ParenthesesNode", &ParenthesesNode{}},
		{"PinnedExpressionNode", &PinnedExpressionNode{}},
		{"PinnedVariableNode", &PinnedVariableNode{}},
		{"PostExecutionNode", &PostExecutionNode{}},
		{"PreExecutionNode", &PreExecutionNode{}},
		{"ProgramNode", &ProgramNode{}},
		{"RangeNode", &RangeNode{}},
		{"RationalNode", &RationalNode{}},
		{"RedoNode", &RedoNode{}},
		{"RegularExpressionNode", &RegularExpressionNode{}},
		{"RequiredKeywordParameterNode", &RequiredKeywordParameterNode{}},
		{"RequiredParameterNode", &RequiredParameterNode{}},
		{"RescueModifierNode", &RescueModifierNode{}},
		{"RescueNode", &RescueNode{}},
		{"RestParameterNode", &RestParameterNode{}},
		{"RetryNode", &RetryNode{}},
		{"ReturnNode", &ReturnNode{}},
		{"SelfNode", &SelfNode{}},
		{"ShareableConstantNode", &ShareableConstantNode{}},
		{"SingletonClassNode", &SingletonClassNode{}},
		{"SourceEncodingNode", &SourceEncodingNode{}},
		{"SourceFileNode", &SourceFileNode{}},
		{"SourceLineNode", &SourceLineNode{}},
		{"SplatNode", &SplatNode{}},
		{"StatementsNode", &StatementsNode{}},
		{"StringNode", &StringNode{}},
		{"SuperNode", &SuperNode{}},
		{"SymbolNode", &SymbolNode{}},
		{"TrueNode", &TrueNode{}},
		{"UndefNode", &UndefNode{}},
		{"UnlessNode", &UnlessNode{}},
		{"UntilNode", &UntilNode{}},
		{"WhenNode", &WhenNode{}},
		{"WhileNode", &WhileNode{}},
		{"XStringNode", &XStringNode{}},
		{"YieldNode", &YieldNode{}},
	}

	for _, tc := range cases {
		recorder := &recordingVisitor{}
		tc.node.Accept(recorder)

		if recorder.visited != "Visit"+tc.name {
			t.Errorf("%s: Accept called %q, want %q", tc.name, recorder.visited, "Visit"+tc.name)
		}
	}
}

// recordingVisitor records which visit method was called. It embeds
// DefaultVisitor so it satisfies the whole interface, and overrides only the
// bookkeeping it needs.
type recordingVisitor struct {
	DefaultVisitor
	visited string
}

func (v *recordingVisitor) VisitChildNodes(Node) {}

func (v *recordingVisitor) VisitAliasGlobalVariableNode(*AliasGlobalVariableNode) {
	v.visited = "VisitAliasGlobalVariableNode"
}
func (v *recordingVisitor) VisitAliasMethodNode(*AliasMethodNode) { v.visited = "VisitAliasMethodNode" }
func (v *recordingVisitor) VisitAlternationPatternNode(*AlternationPatternNode) {
	v.visited = "VisitAlternationPatternNode"
}
func (v *recordingVisitor) VisitAndNode(*AndNode)             { v.visited = "VisitAndNode" }
func (v *recordingVisitor) VisitArgumentsNode(*ArgumentsNode) { v.visited = "VisitArgumentsNode" }
func (v *recordingVisitor) VisitArrayNode(*ArrayNode)         { v.visited = "VisitArrayNode" }
func (v *recordingVisitor) VisitArrayPatternNode(*ArrayPatternNode) {
	v.visited = "VisitArrayPatternNode"
}
func (v *recordingVisitor) VisitAssocNode(*AssocNode)           { v.visited = "VisitAssocNode" }
func (v *recordingVisitor) VisitAssocSplatNode(*AssocSplatNode) { v.visited = "VisitAssocSplatNode" }
func (v *recordingVisitor) VisitBackReferenceReadNode(*BackReferenceReadNode) {
	v.visited = "VisitBackReferenceReadNode"
}
func (v *recordingVisitor) VisitBeginNode(*BeginNode) { v.visited = "VisitBeginNode" }
func (v *recordingVisitor) VisitBlockArgumentNode(*BlockArgumentNode) {
	v.visited = "VisitBlockArgumentNode"
}
func (v *recordingVisitor) VisitBlockLocalVariableNode(*BlockLocalVariableNode) {
	v.visited = "VisitBlockLocalVariableNode"
}
func (v *recordingVisitor) VisitBlockNode(*BlockNode) { v.visited = "VisitBlockNode" }
func (v *recordingVisitor) VisitBlockParameterNode(*BlockParameterNode) {
	v.visited = "VisitBlockParameterNode"
}
func (v *recordingVisitor) VisitBlockParametersNode(*BlockParametersNode) {
	v.visited = "VisitBlockParametersNode"
}
func (v *recordingVisitor) VisitBreakNode(*BreakNode) { v.visited = "VisitBreakNode" }
func (v *recordingVisitor) VisitCallAndWriteNode(*CallAndWriteNode) {
	v.visited = "VisitCallAndWriteNode"
}
func (v *recordingVisitor) VisitCallNode(*CallNode) { v.visited = "VisitCallNode" }
func (v *recordingVisitor) VisitCallOperatorWriteNode(*CallOperatorWriteNode) {
	v.visited = "VisitCallOperatorWriteNode"
}
func (v *recordingVisitor) VisitCallOrWriteNode(*CallOrWriteNode) { v.visited = "VisitCallOrWriteNode" }
func (v *recordingVisitor) VisitCallTargetNode(*CallTargetNode)   { v.visited = "VisitCallTargetNode" }
func (v *recordingVisitor) VisitCapturePatternNode(*CapturePatternNode) {
	v.visited = "VisitCapturePatternNode"
}
func (v *recordingVisitor) VisitCaseMatchNode(*CaseMatchNode) { v.visited = "VisitCaseMatchNode" }
func (v *recordingVisitor) VisitCaseNode(*CaseNode)           { v.visited = "VisitCaseNode" }
func (v *recordingVisitor) VisitClassNode(*ClassNode)         { v.visited = "VisitClassNode" }
func (v *recordingVisitor) VisitClassVariableAndWriteNode(*ClassVariableAndWriteNode) {
	v.visited = "VisitClassVariableAndWriteNode"
}
func (v *recordingVisitor) VisitClassVariableOperatorWriteNode(*ClassVariableOperatorWriteNode) {
	v.visited = "VisitClassVariableOperatorWriteNode"
}
func (v *recordingVisitor) VisitClassVariableOrWriteNode(*ClassVariableOrWriteNode) {
	v.visited = "VisitClassVariableOrWriteNode"
}
func (v *recordingVisitor) VisitClassVariableReadNode(*ClassVariableReadNode) {
	v.visited = "VisitClassVariableReadNode"
}
func (v *recordingVisitor) VisitClassVariableTargetNode(*ClassVariableTargetNode) {
	v.visited = "VisitClassVariableTargetNode"
}
func (v *recordingVisitor) VisitClassVariableWriteNode(*ClassVariableWriteNode) {
	v.visited = "VisitClassVariableWriteNode"
}
func (v *recordingVisitor) VisitConstantAndWriteNode(*ConstantAndWriteNode) {
	v.visited = "VisitConstantAndWriteNode"
}
func (v *recordingVisitor) VisitConstantOperatorWriteNode(*ConstantOperatorWriteNode) {
	v.visited = "VisitConstantOperatorWriteNode"
}
func (v *recordingVisitor) VisitConstantOrWriteNode(*ConstantOrWriteNode) {
	v.visited = "VisitConstantOrWriteNode"
}
func (v *recordingVisitor) VisitConstantPathAndWriteNode(*ConstantPathAndWriteNode) {
	v.visited = "VisitConstantPathAndWriteNode"
}
func (v *recordingVisitor) VisitConstantPathNode(*ConstantPathNode) {
	v.visited = "VisitConstantPathNode"
}
func (v *recordingVisitor) VisitConstantPathOperatorWriteNode(*ConstantPathOperatorWriteNode) {
	v.visited = "VisitConstantPathOperatorWriteNode"
}
func (v *recordingVisitor) VisitConstantPathOrWriteNode(*ConstantPathOrWriteNode) {
	v.visited = "VisitConstantPathOrWriteNode"
}
func (v *recordingVisitor) VisitConstantPathTargetNode(*ConstantPathTargetNode) {
	v.visited = "VisitConstantPathTargetNode"
}
func (v *recordingVisitor) VisitConstantPathWriteNode(*ConstantPathWriteNode) {
	v.visited = "VisitConstantPathWriteNode"
}
func (v *recordingVisitor) VisitConstantReadNode(*ConstantReadNode) {
	v.visited = "VisitConstantReadNode"
}
func (v *recordingVisitor) VisitConstantTargetNode(*ConstantTargetNode) {
	v.visited = "VisitConstantTargetNode"
}
func (v *recordingVisitor) VisitConstantWriteNode(*ConstantWriteNode) {
	v.visited = "VisitConstantWriteNode"
}
func (v *recordingVisitor) VisitDefNode(*DefNode)         { v.visited = "VisitDefNode" }
func (v *recordingVisitor) VisitDefinedNode(*DefinedNode) { v.visited = "VisitDefinedNode" }
func (v *recordingVisitor) VisitElseNode(*ElseNode)       { v.visited = "VisitElseNode" }
func (v *recordingVisitor) VisitEmbeddedStatementsNode(*EmbeddedStatementsNode) {
	v.visited = "VisitEmbeddedStatementsNode"
}
func (v *recordingVisitor) VisitEmbeddedVariableNode(*EmbeddedVariableNode) {
	v.visited = "VisitEmbeddedVariableNode"
}
func (v *recordingVisitor) VisitEnsureNode(*EnsureNode)           { v.visited = "VisitEnsureNode" }
func (v *recordingVisitor) VisitFalseNode(*FalseNode)             { v.visited = "VisitFalseNode" }
func (v *recordingVisitor) VisitFindPatternNode(*FindPatternNode) { v.visited = "VisitFindPatternNode" }
func (v *recordingVisitor) VisitFlipFlopNode(*FlipFlopNode)       { v.visited = "VisitFlipFlopNode" }
func (v *recordingVisitor) VisitFloatNode(*FloatNode)             { v.visited = "VisitFloatNode" }
func (v *recordingVisitor) VisitForNode(*ForNode)                 { v.visited = "VisitForNode" }
func (v *recordingVisitor) VisitForwardingArgumentsNode(*ForwardingArgumentsNode) {
	v.visited = "VisitForwardingArgumentsNode"
}
func (v *recordingVisitor) VisitForwardingParameterNode(*ForwardingParameterNode) {
	v.visited = "VisitForwardingParameterNode"
}
func (v *recordingVisitor) VisitForwardingSuperNode(*ForwardingSuperNode) {
	v.visited = "VisitForwardingSuperNode"
}
func (v *recordingVisitor) VisitGlobalVariableAndWriteNode(*GlobalVariableAndWriteNode) {
	v.visited = "VisitGlobalVariableAndWriteNode"
}
func (v *recordingVisitor) VisitGlobalVariableOperatorWriteNode(*GlobalVariableOperatorWriteNode) {
	v.visited = "VisitGlobalVariableOperatorWriteNode"
}
func (v *recordingVisitor) VisitGlobalVariableOrWriteNode(*GlobalVariableOrWriteNode) {
	v.visited = "VisitGlobalVariableOrWriteNode"
}
func (v *recordingVisitor) VisitGlobalVariableReadNode(*GlobalVariableReadNode) {
	v.visited = "VisitGlobalVariableReadNode"
}
func (v *recordingVisitor) VisitGlobalVariableTargetNode(*GlobalVariableTargetNode) {
	v.visited = "VisitGlobalVariableTargetNode"
}
func (v *recordingVisitor) VisitGlobalVariableWriteNode(*GlobalVariableWriteNode) {
	v.visited = "VisitGlobalVariableWriteNode"
}
func (v *recordingVisitor) VisitHashNode(*HashNode)               { v.visited = "VisitHashNode" }
func (v *recordingVisitor) VisitHashPatternNode(*HashPatternNode) { v.visited = "VisitHashPatternNode" }
func (v *recordingVisitor) VisitIfNode(*IfNode)                   { v.visited = "VisitIfNode" }
func (v *recordingVisitor) VisitImaginaryNode(*ImaginaryNode)     { v.visited = "VisitImaginaryNode" }
func (v *recordingVisitor) VisitImplicitNode(*ImplicitNode)       { v.visited = "VisitImplicitNode" }
func (v *recordingVisitor) VisitImplicitRestNode(*ImplicitRestNode) {
	v.visited = "VisitImplicitRestNode"
}
func (v *recordingVisitor) VisitInNode(*InNode) { v.visited = "VisitInNode" }
func (v *recordingVisitor) VisitIndexAndWriteNode(*IndexAndWriteNode) {
	v.visited = "VisitIndexAndWriteNode"
}
func (v *recordingVisitor) VisitIndexOperatorWriteNode(*IndexOperatorWriteNode) {
	v.visited = "VisitIndexOperatorWriteNode"
}
func (v *recordingVisitor) VisitIndexOrWriteNode(*IndexOrWriteNode) {
	v.visited = "VisitIndexOrWriteNode"
}
func (v *recordingVisitor) VisitIndexTargetNode(*IndexTargetNode) { v.visited = "VisitIndexTargetNode" }
func (v *recordingVisitor) VisitInstanceVariableAndWriteNode(*InstanceVariableAndWriteNode) {
	v.visited = "VisitInstanceVariableAndWriteNode"
}
func (v *recordingVisitor) VisitInstanceVariableOperatorWriteNode(*InstanceVariableOperatorWriteNode) {
	v.visited = "VisitInstanceVariableOperatorWriteNode"
}
func (v *recordingVisitor) VisitInstanceVariableOrWriteNode(*InstanceVariableOrWriteNode) {
	v.visited = "VisitInstanceVariableOrWriteNode"
}
func (v *recordingVisitor) VisitInstanceVariableReadNode(*InstanceVariableReadNode) {
	v.visited = "VisitInstanceVariableReadNode"
}
func (v *recordingVisitor) VisitInstanceVariableTargetNode(*InstanceVariableTargetNode) {
	v.visited = "VisitInstanceVariableTargetNode"
}
func (v *recordingVisitor) VisitInstanceVariableWriteNode(*InstanceVariableWriteNode) {
	v.visited = "VisitInstanceVariableWriteNode"
}
func (v *recordingVisitor) VisitIntegerNode(*IntegerNode) { v.visited = "VisitIntegerNode" }
func (v *recordingVisitor) VisitInterpolatedMatchLastLineNode(*InterpolatedMatchLastLineNode) {
	v.visited = "VisitInterpolatedMatchLastLineNode"
}
func (v *recordingVisitor) VisitInterpolatedRegularExpressionNode(*InterpolatedRegularExpressionNode) {
	v.visited = "VisitInterpolatedRegularExpressionNode"
}
func (v *recordingVisitor) VisitInterpolatedStringNode(*InterpolatedStringNode) {
	v.visited = "VisitInterpolatedStringNode"
}
func (v *recordingVisitor) VisitInterpolatedSymbolNode(*InterpolatedSymbolNode) {
	v.visited = "VisitInterpolatedSymbolNode"
}
func (v *recordingVisitor) VisitInterpolatedXStringNode(*InterpolatedXStringNode) {
	v.visited = "VisitInterpolatedXStringNode"
}
func (v *recordingVisitor) VisitItLocalVariableReadNode(*ItLocalVariableReadNode) {
	v.visited = "VisitItLocalVariableReadNode"
}
func (v *recordingVisitor) VisitItParametersNode(*ItParametersNode) {
	v.visited = "VisitItParametersNode"
}
func (v *recordingVisitor) VisitKeywordHashNode(*KeywordHashNode) { v.visited = "VisitKeywordHashNode" }
func (v *recordingVisitor) VisitKeywordRestParameterNode(*KeywordRestParameterNode) {
	v.visited = "VisitKeywordRestParameterNode"
}
func (v *recordingVisitor) VisitLambdaNode(*LambdaNode) { v.visited = "VisitLambdaNode" }
func (v *recordingVisitor) VisitLocalVariableAndWriteNode(*LocalVariableAndWriteNode) {
	v.visited = "VisitLocalVariableAndWriteNode"
}
func (v *recordingVisitor) VisitLocalVariableOperatorWriteNode(*LocalVariableOperatorWriteNode) {
	v.visited = "VisitLocalVariableOperatorWriteNode"
}
func (v *recordingVisitor) VisitLocalVariableOrWriteNode(*LocalVariableOrWriteNode) {
	v.visited = "VisitLocalVariableOrWriteNode"
}
func (v *recordingVisitor) VisitLocalVariableReadNode(*LocalVariableReadNode) {
	v.visited = "VisitLocalVariableReadNode"
}
func (v *recordingVisitor) VisitLocalVariableTargetNode(*LocalVariableTargetNode) {
	v.visited = "VisitLocalVariableTargetNode"
}
func (v *recordingVisitor) VisitLocalVariableWriteNode(*LocalVariableWriteNode) {
	v.visited = "VisitLocalVariableWriteNode"
}
func (v *recordingVisitor) VisitMatchLastLineNode(*MatchLastLineNode) {
	v.visited = "VisitMatchLastLineNode"
}
func (v *recordingVisitor) VisitMatchPredicateNode(*MatchPredicateNode) {
	v.visited = "VisitMatchPredicateNode"
}
func (v *recordingVisitor) VisitMatchRequiredNode(*MatchRequiredNode) {
	v.visited = "VisitMatchRequiredNode"
}
func (v *recordingVisitor) VisitMatchWriteNode(*MatchWriteNode)   { v.visited = "VisitMatchWriteNode" }
func (v *recordingVisitor) VisitMissingNode(*MissingNode)         { v.visited = "VisitMissingNode" }
func (v *recordingVisitor) VisitModuleNode(*ModuleNode)           { v.visited = "VisitModuleNode" }
func (v *recordingVisitor) VisitMultiTargetNode(*MultiTargetNode) { v.visited = "VisitMultiTargetNode" }
func (v *recordingVisitor) VisitMultiWriteNode(*MultiWriteNode)   { v.visited = "VisitMultiWriteNode" }
func (v *recordingVisitor) VisitNextNode(*NextNode)               { v.visited = "VisitNextNode" }
func (v *recordingVisitor) VisitNilNode(*NilNode)                 { v.visited = "VisitNilNode" }
func (v *recordingVisitor) VisitNoKeywordsParameterNode(*NoKeywordsParameterNode) {
	v.visited = "VisitNoKeywordsParameterNode"
}
func (v *recordingVisitor) VisitNumberedParametersNode(*NumberedParametersNode) {
	v.visited = "VisitNumberedParametersNode"
}
func (v *recordingVisitor) VisitNumberedReferenceReadNode(*NumberedReferenceReadNode) {
	v.visited = "VisitNumberedReferenceReadNode"
}
func (v *recordingVisitor) VisitOptionalKeywordParameterNode(*OptionalKeywordParameterNode) {
	v.visited = "VisitOptionalKeywordParameterNode"
}
func (v *recordingVisitor) VisitOptionalParameterNode(*OptionalParameterNode) {
	v.visited = "VisitOptionalParameterNode"
}
func (v *recordingVisitor) VisitOrNode(*OrNode)                   { v.visited = "VisitOrNode" }
func (v *recordingVisitor) VisitParametersNode(*ParametersNode)   { v.visited = "VisitParametersNode" }
func (v *recordingVisitor) VisitParenthesesNode(*ParenthesesNode) { v.visited = "VisitParenthesesNode" }
func (v *recordingVisitor) VisitPinnedExpressionNode(*PinnedExpressionNode) {
	v.visited = "VisitPinnedExpressionNode"
}
func (v *recordingVisitor) VisitPinnedVariableNode(*PinnedVariableNode) {
	v.visited = "VisitPinnedVariableNode"
}
func (v *recordingVisitor) VisitPostExecutionNode(*PostExecutionNode) {
	v.visited = "VisitPostExecutionNode"
}
func (v *recordingVisitor) VisitPreExecutionNode(*PreExecutionNode) {
	v.visited = "VisitPreExecutionNode"
}
func (v *recordingVisitor) VisitProgramNode(*ProgramNode)   { v.visited = "VisitProgramNode" }
func (v *recordingVisitor) VisitRangeNode(*RangeNode)       { v.visited = "VisitRangeNode" }
func (v *recordingVisitor) VisitRationalNode(*RationalNode) { v.visited = "VisitRationalNode" }
func (v *recordingVisitor) VisitRedoNode(*RedoNode)         { v.visited = "VisitRedoNode" }
func (v *recordingVisitor) VisitRegularExpressionNode(*RegularExpressionNode) {
	v.visited = "VisitRegularExpressionNode"
}
func (v *recordingVisitor) VisitRequiredKeywordParameterNode(*RequiredKeywordParameterNode) {
	v.visited = "VisitRequiredKeywordParameterNode"
}
func (v *recordingVisitor) VisitRequiredParameterNode(*RequiredParameterNode) {
	v.visited = "VisitRequiredParameterNode"
}
func (v *recordingVisitor) VisitRescueModifierNode(*RescueModifierNode) {
	v.visited = "VisitRescueModifierNode"
}
func (v *recordingVisitor) VisitRescueNode(*RescueNode) { v.visited = "VisitRescueNode" }
func (v *recordingVisitor) VisitRestParameterNode(*RestParameterNode) {
	v.visited = "VisitRestParameterNode"
}
func (v *recordingVisitor) VisitRetryNode(*RetryNode)   { v.visited = "VisitRetryNode" }
func (v *recordingVisitor) VisitReturnNode(*ReturnNode) { v.visited = "VisitReturnNode" }
func (v *recordingVisitor) VisitSelfNode(*SelfNode)     { v.visited = "VisitSelfNode" }
func (v *recordingVisitor) VisitShareableConstantNode(*ShareableConstantNode) {
	v.visited = "VisitShareableConstantNode"
}
func (v *recordingVisitor) VisitSingletonClassNode(*SingletonClassNode) {
	v.visited = "VisitSingletonClassNode"
}
func (v *recordingVisitor) VisitSourceEncodingNode(*SourceEncodingNode) {
	v.visited = "VisitSourceEncodingNode"
}
func (v *recordingVisitor) VisitSourceFileNode(*SourceFileNode) { v.visited = "VisitSourceFileNode" }
func (v *recordingVisitor) VisitSourceLineNode(*SourceLineNode) { v.visited = "VisitSourceLineNode" }
func (v *recordingVisitor) VisitSplatNode(*SplatNode)           { v.visited = "VisitSplatNode" }
func (v *recordingVisitor) VisitStatementsNode(*StatementsNode) { v.visited = "VisitStatementsNode" }
func (v *recordingVisitor) VisitStringNode(*StringNode)         { v.visited = "VisitStringNode" }
func (v *recordingVisitor) VisitSuperNode(*SuperNode)           { v.visited = "VisitSuperNode" }
func (v *recordingVisitor) VisitSymbolNode(*SymbolNode)         { v.visited = "VisitSymbolNode" }
func (v *recordingVisitor) VisitTrueNode(*TrueNode)             { v.visited = "VisitTrueNode" }
func (v *recordingVisitor) VisitUndefNode(*UndefNode)           { v.visited = "VisitUndefNode" }
func (v *recordingVisitor) VisitUnlessNode(*UnlessNode)         { v.visited = "VisitUnlessNode" }
func (v *recordingVisitor) VisitUntilNode(*UntilNode)           { v.visited = "VisitUntilNode" }
func (v *recordingVisitor) VisitWhenNode(*WhenNode)             { v.visited = "VisitWhenNode" }
func (v *recordingVisitor) VisitWhileNode(*WhileNode)           { v.visited = "VisitWhileNode" }
func (v *recordingVisitor) VisitXStringNode(*XStringNode)       { v.visited = "VisitXStringNode" }
func (v *recordingVisitor) VisitYieldNode(*YieldNode)           { v.visited = "VisitYieldNode" }
