/*----------------------------------------------------------------------------*/
/* This file is generated by the templates/template.rb script and should not  */
/* be modified manually. See                                                  */
/* templates/../../templates/gen_warning.go.erb                               */
/* if you are looking to modify the                                           */
/* template                                                                   */
/*----------------------------------------------------------------------------*/

package parser

type WarningLevel int
type WarningType int

const (
	WarningDefault WarningLevel = iota
	WarningVerbose
)

const (
	AMBIGUOUS_BINARY_OPERATOR_WARNING      WarningType = 0
	AMBIGUOUS_FIRST_ARGUMENT_MINUS_WARNING WarningType = 1
	AMBIGUOUS_FIRST_ARGUMENT_PLUS_WARNING  WarningType = 2
	AMBIGUOUS_PREFIX_AMPERSAND_WARNING     WarningType = 3
	AMBIGUOUS_PREFIX_STAR_WARNING          WarningType = 4
	AMBIGUOUS_PREFIX_STAR_STAR_WARNING     WarningType = 5
	AMBIGUOUS_SLASH_WARNING                WarningType = 6
	COMPARISON_AFTER_COMPARISON_WARNING    WarningType = 7
	DOT_DOT_DOT_EOL_WARNING                WarningType = 8
	EQUAL_IN_CONDITIONAL_WARNING           WarningType = 9
	EQUAL_IN_CONDITIONAL_3_3_WARNING       WarningType = 10
	END_IN_METHOD_WARNING                  WarningType = 11
	DUPLICATED_HASH_KEY_WARNING            WarningType = 12
	DUPLICATED_WHEN_CLAUSE_WARNING         WarningType = 13
	FLOAT_OUT_OF_RANGE_WARNING             WarningType = 14
	IGNORED_FROZEN_STRING_LITERAL_WARNING  WarningType = 15
	INDENTATION_MISMATCH_WARNING           WarningType = 16
	INTEGER_IN_FLIP_FLOP_WARNING           WarningType = 17
	INVALID_CHARACTER_WARNING              WarningType = 18
	INVALID_MAGIC_COMMENT_VALUE_WARNING    WarningType = 19
	INVALID_NUMBERED_REFERENCE_WARNING     WarningType = 20
	KEYWORD_EOL_WARNING                    WarningType = 21
	LITERAL_IN_CONDITION_DEFAULT_WARNING   WarningType = 22
	LITERAL_IN_CONDITION_VERBOSE_WARNING   WarningType = 23
	SHAREABLE_CONSTANT_VALUE_LINE_WARNING  WarningType = 24
	SHEBANG_CARRIAGE_RETURN_WARNING        WarningType = 25
	UNEXPECTED_CARRIAGE_RETURN_WARNING     WarningType = 26
	UNREACHABLE_STATEMENT_WARNING          WarningType = 27
	UNUSED_LOCAL_VARIABLE_WARNING          WarningType = 28
	VOID_STATEMENT_WARNING                 WarningType = 29
)

var WarningLevels = []WarningLevel{WarningDefault, WarningVerbose}
var WarningTypes = []WarningType{
	AMBIGUOUS_BINARY_OPERATOR_WARNING,
	AMBIGUOUS_FIRST_ARGUMENT_MINUS_WARNING,
	AMBIGUOUS_FIRST_ARGUMENT_PLUS_WARNING,
	AMBIGUOUS_PREFIX_AMPERSAND_WARNING,
	AMBIGUOUS_PREFIX_STAR_WARNING,
	AMBIGUOUS_PREFIX_STAR_STAR_WARNING,
	AMBIGUOUS_SLASH_WARNING,
	COMPARISON_AFTER_COMPARISON_WARNING,
	DOT_DOT_DOT_EOL_WARNING,
	EQUAL_IN_CONDITIONAL_WARNING,
	EQUAL_IN_CONDITIONAL_3_3_WARNING,
	END_IN_METHOD_WARNING,
	DUPLICATED_HASH_KEY_WARNING,
	DUPLICATED_WHEN_CLAUSE_WARNING,
	FLOAT_OUT_OF_RANGE_WARNING,
	IGNORED_FROZEN_STRING_LITERAL_WARNING,
	INDENTATION_MISMATCH_WARNING,
	INTEGER_IN_FLIP_FLOP_WARNING,
	INVALID_CHARACTER_WARNING,
	INVALID_MAGIC_COMMENT_VALUE_WARNING,
	INVALID_NUMBERED_REFERENCE_WARNING,
	KEYWORD_EOL_WARNING,
	LITERAL_IN_CONDITION_DEFAULT_WARNING,
	LITERAL_IN_CONDITION_VERBOSE_WARNING,
	SHAREABLE_CONSTANT_VALUE_LINE_WARNING,
	SHEBANG_CARRIAGE_RETURN_WARNING,
	UNEXPECTED_CARRIAGE_RETURN_WARNING,
	UNREACHABLE_STATEMENT_WARNING,
	UNUSED_LOCAL_VARIABLE_WARNING,
	VOID_STATEMENT_WARNING,
}

type Warning struct {
	Message  string
	Location *Location
	Level    WarningLevel
	Type     WarningType
}

func NewWarning(
	message string,
	location *Location,
	level WarningLevel,
	warnType WarningType,
) *Warning {
	return &Warning{
		Message:  message,
		Location: location,
		Level:    level,
		Type:     warnType,
	}
}
