/*----------------------------------------------------------------------------*/
/* This file is generated by the templates/template.rb script and should not  */
/* be modified manually. See                                                  */
/* templates/../../templates/gen_visitor.go.erb                               */
/* if you are looking to modify the                                           */
/* template                                                                   */
/*----------------------------------------------------------------------------*/

package parser

// BasicVisitor provides the interface for walking down the tree. None of the individual visit
// methods are implemented on this interface, so it forces the consumer to
// implement each one that they need. For a default implementation that
// continues walking the tree, see the `Visitor` interface and `DefaultVisitor` struct.
type BasicVisitor interface {
	// Visit calls Accept on the given node if it is not nil, which in turn should
	// call back into this visitor by calling the appropriate Visit* method.
	Visit(node Node)

	// VisitAll visits each node in the slice by calling Accept on each one.
	VisitAll(nodes []Node)

	// VisitChildNodes visits the child nodes of the given node by calling Accept on each one.
	VisitChildNodes(node Node)
}

// Visitor provides a default implementation for every visit method defined on the nodes.
// This means it can walk a tree without the caller needing to define any special handling.
// This allows you to handle a subset of the tree, while still walking the whole tree.
//
// For example, to find all of the method calls that call the "foo" method, you
// could implement:
//
//	type FooCallVisitor struct {
//		DefaultVisitor
//		FooCalls []*CallNode
//	}
//
//	func (v *FooCallVisitor) VisitCallNode(node *CallNode) {
//		if node.Name == "foo" {
//			v.FooCalls = append(v.FooCalls, node)
//		}
//		// Call the default implementation to continue walking the tree
//		v.DefaultVisitor.VisitCallNode(node)
//	}
type Visitor interface {
	BasicVisitor

	// VisitAliasGlobalVariableNode visits a AliasGlobalVariableNode node.
	VisitAliasGlobalVariableNode(node *AliasGlobalVariableNode)

	// VisitAliasMethodNode visits a AliasMethodNode node.
	VisitAliasMethodNode(node *AliasMethodNode)

	// VisitAlternationPatternNode visits a AlternationPatternNode node.
	VisitAlternationPatternNode(node *AlternationPatternNode)

	// VisitAndNode visits a AndNode node.
	VisitAndNode(node *AndNode)

	// VisitArgumentsNode visits a ArgumentsNode node.
	VisitArgumentsNode(node *ArgumentsNode)

	// VisitArrayNode visits a ArrayNode node.
	VisitArrayNode(node *ArrayNode)

	// VisitArrayPatternNode visits a ArrayPatternNode node.
	VisitArrayPatternNode(node *ArrayPatternNode)

	// VisitAssocNode visits a AssocNode node.
	VisitAssocNode(node *AssocNode)

	// VisitAssocSplatNode visits a AssocSplatNode node.
	VisitAssocSplatNode(node *AssocSplatNode)

	// VisitBackReferenceReadNode visits a BackReferenceReadNode node.
	VisitBackReferenceReadNode(node *BackReferenceReadNode)

	// VisitBeginNode visits a BeginNode node.
	VisitBeginNode(node *BeginNode)

	// VisitBlockArgumentNode visits a BlockArgumentNode node.
	VisitBlockArgumentNode(node *BlockArgumentNode)

	// VisitBlockLocalVariableNode visits a BlockLocalVariableNode node.
	VisitBlockLocalVariableNode(node *BlockLocalVariableNode)

	// VisitBlockNode visits a BlockNode node.
	VisitBlockNode(node *BlockNode)

	// VisitBlockParameterNode visits a BlockParameterNode node.
	VisitBlockParameterNode(node *BlockParameterNode)

	// VisitBlockParametersNode visits a BlockParametersNode node.
	VisitBlockParametersNode(node *BlockParametersNode)

	// VisitBreakNode visits a BreakNode node.
	VisitBreakNode(node *BreakNode)

	// VisitCallAndWriteNode visits a CallAndWriteNode node.
	VisitCallAndWriteNode(node *CallAndWriteNode)

	// VisitCallNode visits a CallNode node.
	VisitCallNode(node *CallNode)

	// VisitCallOperatorWriteNode visits a CallOperatorWriteNode node.
	VisitCallOperatorWriteNode(node *CallOperatorWriteNode)

	// VisitCallOrWriteNode visits a CallOrWriteNode node.
	VisitCallOrWriteNode(node *CallOrWriteNode)

	// VisitCallTargetNode visits a CallTargetNode node.
	VisitCallTargetNode(node *CallTargetNode)

	// VisitCapturePatternNode visits a CapturePatternNode node.
	VisitCapturePatternNode(node *CapturePatternNode)

	// VisitCaseMatchNode visits a CaseMatchNode node.
	VisitCaseMatchNode(node *CaseMatchNode)

	// VisitCaseNode visits a CaseNode node.
	VisitCaseNode(node *CaseNode)

	// VisitClassNode visits a ClassNode node.
	VisitClassNode(node *ClassNode)

	// VisitClassVariableAndWriteNode visits a ClassVariableAndWriteNode node.
	VisitClassVariableAndWriteNode(node *ClassVariableAndWriteNode)

	// VisitClassVariableOperatorWriteNode visits a ClassVariableOperatorWriteNode node.
	VisitClassVariableOperatorWriteNode(node *ClassVariableOperatorWriteNode)

	// VisitClassVariableOrWriteNode visits a ClassVariableOrWriteNode node.
	VisitClassVariableOrWriteNode(node *ClassVariableOrWriteNode)

	// VisitClassVariableReadNode visits a ClassVariableReadNode node.
	VisitClassVariableReadNode(node *ClassVariableReadNode)

	// VisitClassVariableTargetNode visits a ClassVariableTargetNode node.
	VisitClassVariableTargetNode(node *ClassVariableTargetNode)

	// VisitClassVariableWriteNode visits a ClassVariableWriteNode node.
	VisitClassVariableWriteNode(node *ClassVariableWriteNode)

	// VisitConstantAndWriteNode visits a ConstantAndWriteNode node.
	VisitConstantAndWriteNode(node *ConstantAndWriteNode)

	// VisitConstantOperatorWriteNode visits a ConstantOperatorWriteNode node.
	VisitConstantOperatorWriteNode(node *ConstantOperatorWriteNode)

	// VisitConstantOrWriteNode visits a ConstantOrWriteNode node.
	VisitConstantOrWriteNode(node *ConstantOrWriteNode)

	// VisitConstantPathAndWriteNode visits a ConstantPathAndWriteNode node.
	VisitConstantPathAndWriteNode(node *ConstantPathAndWriteNode)

	// VisitConstantPathNode visits a ConstantPathNode node.
	VisitConstantPathNode(node *ConstantPathNode)

	// VisitConstantPathOperatorWriteNode visits a ConstantPathOperatorWriteNode node.
	VisitConstantPathOperatorWriteNode(node *ConstantPathOperatorWriteNode)

	// VisitConstantPathOrWriteNode visits a ConstantPathOrWriteNode node.
	VisitConstantPathOrWriteNode(node *ConstantPathOrWriteNode)

	// VisitConstantPathTargetNode visits a ConstantPathTargetNode node.
	VisitConstantPathTargetNode(node *ConstantPathTargetNode)

	// VisitConstantPathWriteNode visits a ConstantPathWriteNode node.
	VisitConstantPathWriteNode(node *ConstantPathWriteNode)

	// VisitConstantReadNode visits a ConstantReadNode node.
	VisitConstantReadNode(node *ConstantReadNode)

	// VisitConstantTargetNode visits a ConstantTargetNode node.
	VisitConstantTargetNode(node *ConstantTargetNode)

	// VisitConstantWriteNode visits a ConstantWriteNode node.
	VisitConstantWriteNode(node *ConstantWriteNode)

	// VisitDefNode visits a DefNode node.
	VisitDefNode(node *DefNode)

	// VisitDefinedNode visits a DefinedNode node.
	VisitDefinedNode(node *DefinedNode)

	// VisitElseNode visits a ElseNode node.
	VisitElseNode(node *ElseNode)

	// VisitEmbeddedStatementsNode visits a EmbeddedStatementsNode node.
	VisitEmbeddedStatementsNode(node *EmbeddedStatementsNode)

	// VisitEmbeddedVariableNode visits a EmbeddedVariableNode node.
	VisitEmbeddedVariableNode(node *EmbeddedVariableNode)

	// VisitEnsureNode visits a EnsureNode node.
	VisitEnsureNode(node *EnsureNode)

	// VisitFalseNode visits a FalseNode node.
	VisitFalseNode(node *FalseNode)

	// VisitFindPatternNode visits a FindPatternNode node.
	VisitFindPatternNode(node *FindPatternNode)

	// VisitFlipFlopNode visits a FlipFlopNode node.
	VisitFlipFlopNode(node *FlipFlopNode)

	// VisitFloatNode visits a FloatNode node.
	VisitFloatNode(node *FloatNode)

	// VisitForNode visits a ForNode node.
	VisitForNode(node *ForNode)

	// VisitForwardingArgumentsNode visits a ForwardingArgumentsNode node.
	VisitForwardingArgumentsNode(node *ForwardingArgumentsNode)

	// VisitForwardingParameterNode visits a ForwardingParameterNode node.
	VisitForwardingParameterNode(node *ForwardingParameterNode)

	// VisitForwardingSuperNode visits a ForwardingSuperNode node.
	VisitForwardingSuperNode(node *ForwardingSuperNode)

	// VisitGlobalVariableAndWriteNode visits a GlobalVariableAndWriteNode node.
	VisitGlobalVariableAndWriteNode(node *GlobalVariableAndWriteNode)

	// VisitGlobalVariableOperatorWriteNode visits a GlobalVariableOperatorWriteNode node.
	VisitGlobalVariableOperatorWriteNode(node *GlobalVariableOperatorWriteNode)

	// VisitGlobalVariableOrWriteNode visits a GlobalVariableOrWriteNode node.
	VisitGlobalVariableOrWriteNode(node *GlobalVariableOrWriteNode)

	// VisitGlobalVariableReadNode visits a GlobalVariableReadNode node.
	VisitGlobalVariableReadNode(node *GlobalVariableReadNode)

	// VisitGlobalVariableTargetNode visits a GlobalVariableTargetNode node.
	VisitGlobalVariableTargetNode(node *GlobalVariableTargetNode)

	// VisitGlobalVariableWriteNode visits a GlobalVariableWriteNode node.
	VisitGlobalVariableWriteNode(node *GlobalVariableWriteNode)

	// VisitHashNode visits a HashNode node.
	VisitHashNode(node *HashNode)

	// VisitHashPatternNode visits a HashPatternNode node.
	VisitHashPatternNode(node *HashPatternNode)

	// VisitIfNode visits a IfNode node.
	VisitIfNode(node *IfNode)

	// VisitImaginaryNode visits a ImaginaryNode node.
	VisitImaginaryNode(node *ImaginaryNode)

	// VisitImplicitNode visits a ImplicitNode node.
	VisitImplicitNode(node *ImplicitNode)

	// VisitImplicitRestNode visits a ImplicitRestNode node.
	VisitImplicitRestNode(node *ImplicitRestNode)

	// VisitInNode visits a InNode node.
	VisitInNode(node *InNode)

	// VisitIndexAndWriteNode visits a IndexAndWriteNode node.
	VisitIndexAndWriteNode(node *IndexAndWriteNode)

	// VisitIndexOperatorWriteNode visits a IndexOperatorWriteNode node.
	VisitIndexOperatorWriteNode(node *IndexOperatorWriteNode)

	// VisitIndexOrWriteNode visits a IndexOrWriteNode node.
	VisitIndexOrWriteNode(node *IndexOrWriteNode)

	// VisitIndexTargetNode visits a IndexTargetNode node.
	VisitIndexTargetNode(node *IndexTargetNode)

	// VisitInstanceVariableAndWriteNode visits a InstanceVariableAndWriteNode node.
	VisitInstanceVariableAndWriteNode(node *InstanceVariableAndWriteNode)

	// VisitInstanceVariableOperatorWriteNode visits a InstanceVariableOperatorWriteNode node.
	VisitInstanceVariableOperatorWriteNode(node *InstanceVariableOperatorWriteNode)

	// VisitInstanceVariableOrWriteNode visits a InstanceVariableOrWriteNode node.
	VisitInstanceVariableOrWriteNode(node *InstanceVariableOrWriteNode)

	// VisitInstanceVariableReadNode visits a InstanceVariableReadNode node.
	VisitInstanceVariableReadNode(node *InstanceVariableReadNode)

	// VisitInstanceVariableTargetNode visits a InstanceVariableTargetNode node.
	VisitInstanceVariableTargetNode(node *InstanceVariableTargetNode)

	// VisitInstanceVariableWriteNode visits a InstanceVariableWriteNode node.
	VisitInstanceVariableWriteNode(node *InstanceVariableWriteNode)

	// VisitIntegerNode visits a IntegerNode node.
	VisitIntegerNode(node *IntegerNode)

	// VisitInterpolatedMatchLastLineNode visits a InterpolatedMatchLastLineNode node.
	VisitInterpolatedMatchLastLineNode(node *InterpolatedMatchLastLineNode)

	// VisitInterpolatedRegularExpressionNode visits a InterpolatedRegularExpressionNode node.
	VisitInterpolatedRegularExpressionNode(node *InterpolatedRegularExpressionNode)

	// VisitInterpolatedStringNode visits a InterpolatedStringNode node.
	VisitInterpolatedStringNode(node *InterpolatedStringNode)

	// VisitInterpolatedSymbolNode visits a InterpolatedSymbolNode node.
	VisitInterpolatedSymbolNode(node *InterpolatedSymbolNode)

	// VisitInterpolatedXStringNode visits a InterpolatedXStringNode node.
	VisitInterpolatedXStringNode(node *InterpolatedXStringNode)

	// VisitItLocalVariableReadNode visits a ItLocalVariableReadNode node.
	VisitItLocalVariableReadNode(node *ItLocalVariableReadNode)

	// VisitItParametersNode visits a ItParametersNode node.
	VisitItParametersNode(node *ItParametersNode)

	// VisitKeywordHashNode visits a KeywordHashNode node.
	VisitKeywordHashNode(node *KeywordHashNode)

	// VisitKeywordRestParameterNode visits a KeywordRestParameterNode node.
	VisitKeywordRestParameterNode(node *KeywordRestParameterNode)

	// VisitLambdaNode visits a LambdaNode node.
	VisitLambdaNode(node *LambdaNode)

	// VisitLocalVariableAndWriteNode visits a LocalVariableAndWriteNode node.
	VisitLocalVariableAndWriteNode(node *LocalVariableAndWriteNode)

	// VisitLocalVariableOperatorWriteNode visits a LocalVariableOperatorWriteNode node.
	VisitLocalVariableOperatorWriteNode(node *LocalVariableOperatorWriteNode)

	// VisitLocalVariableOrWriteNode visits a LocalVariableOrWriteNode node.
	VisitLocalVariableOrWriteNode(node *LocalVariableOrWriteNode)

	// VisitLocalVariableReadNode visits a LocalVariableReadNode node.
	VisitLocalVariableReadNode(node *LocalVariableReadNode)

	// VisitLocalVariableTargetNode visits a LocalVariableTargetNode node.
	VisitLocalVariableTargetNode(node *LocalVariableTargetNode)

	// VisitLocalVariableWriteNode visits a LocalVariableWriteNode node.
	VisitLocalVariableWriteNode(node *LocalVariableWriteNode)

	// VisitMatchLastLineNode visits a MatchLastLineNode node.
	VisitMatchLastLineNode(node *MatchLastLineNode)

	// VisitMatchPredicateNode visits a MatchPredicateNode node.
	VisitMatchPredicateNode(node *MatchPredicateNode)

	// VisitMatchRequiredNode visits a MatchRequiredNode node.
	VisitMatchRequiredNode(node *MatchRequiredNode)

	// VisitMatchWriteNode visits a MatchWriteNode node.
	VisitMatchWriteNode(node *MatchWriteNode)

	// VisitMissingNode visits a MissingNode node.
	VisitMissingNode(node *MissingNode)

	// VisitModuleNode visits a ModuleNode node.
	VisitModuleNode(node *ModuleNode)

	// VisitMultiTargetNode visits a MultiTargetNode node.
	VisitMultiTargetNode(node *MultiTargetNode)

	// VisitMultiWriteNode visits a MultiWriteNode node.
	VisitMultiWriteNode(node *MultiWriteNode)

	// VisitNextNode visits a NextNode node.
	VisitNextNode(node *NextNode)

	// VisitNilNode visits a NilNode node.
	VisitNilNode(node *NilNode)

	// VisitNoKeywordsParameterNode visits a NoKeywordsParameterNode node.
	VisitNoKeywordsParameterNode(node *NoKeywordsParameterNode)

	// VisitNumberedParametersNode visits a NumberedParametersNode node.
	VisitNumberedParametersNode(node *NumberedParametersNode)

	// VisitNumberedReferenceReadNode visits a NumberedReferenceReadNode node.
	VisitNumberedReferenceReadNode(node *NumberedReferenceReadNode)

	// VisitOptionalKeywordParameterNode visits a OptionalKeywordParameterNode node.
	VisitOptionalKeywordParameterNode(node *OptionalKeywordParameterNode)

	// VisitOptionalParameterNode visits a OptionalParameterNode node.
	VisitOptionalParameterNode(node *OptionalParameterNode)

	// VisitOrNode visits a OrNode node.
	VisitOrNode(node *OrNode)

	// VisitParametersNode visits a ParametersNode node.
	VisitParametersNode(node *ParametersNode)

	// VisitParenthesesNode visits a ParenthesesNode node.
	VisitParenthesesNode(node *ParenthesesNode)

	// VisitPinnedExpressionNode visits a PinnedExpressionNode node.
	VisitPinnedExpressionNode(node *PinnedExpressionNode)

	// VisitPinnedVariableNode visits a PinnedVariableNode node.
	VisitPinnedVariableNode(node *PinnedVariableNode)

	// VisitPostExecutionNode visits a PostExecutionNode node.
	VisitPostExecutionNode(node *PostExecutionNode)

	// VisitPreExecutionNode visits a PreExecutionNode node.
	VisitPreExecutionNode(node *PreExecutionNode)

	// VisitProgramNode visits a ProgramNode node.
	VisitProgramNode(node *ProgramNode)

	// VisitRangeNode visits a RangeNode node.
	VisitRangeNode(node *RangeNode)

	// VisitRationalNode visits a RationalNode node.
	VisitRationalNode(node *RationalNode)

	// VisitRedoNode visits a RedoNode node.
	VisitRedoNode(node *RedoNode)

	// VisitRegularExpressionNode visits a RegularExpressionNode node.
	VisitRegularExpressionNode(node *RegularExpressionNode)

	// VisitRequiredKeywordParameterNode visits a RequiredKeywordParameterNode node.
	VisitRequiredKeywordParameterNode(node *RequiredKeywordParameterNode)

	// VisitRequiredParameterNode visits a RequiredParameterNode node.
	VisitRequiredParameterNode(node *RequiredParameterNode)

	// VisitRescueModifierNode visits a RescueModifierNode node.
	VisitRescueModifierNode(node *RescueModifierNode)

	// VisitRescueNode visits a RescueNode node.
	VisitRescueNode(node *RescueNode)

	// VisitRestParameterNode visits a RestParameterNode node.
	VisitRestParameterNode(node *RestParameterNode)

	// VisitRetryNode visits a RetryNode node.
	VisitRetryNode(node *RetryNode)

	// VisitReturnNode visits a ReturnNode node.
	VisitReturnNode(node *ReturnNode)

	// VisitSelfNode visits a SelfNode node.
	VisitSelfNode(node *SelfNode)

	// VisitShareableConstantNode visits a ShareableConstantNode node.
	VisitShareableConstantNode(node *ShareableConstantNode)

	// VisitSingletonClassNode visits a SingletonClassNode node.
	VisitSingletonClassNode(node *SingletonClassNode)

	// VisitSourceEncodingNode visits a SourceEncodingNode node.
	VisitSourceEncodingNode(node *SourceEncodingNode)

	// VisitSourceFileNode visits a SourceFileNode node.
	VisitSourceFileNode(node *SourceFileNode)

	// VisitSourceLineNode visits a SourceLineNode node.
	VisitSourceLineNode(node *SourceLineNode)

	// VisitSplatNode visits a SplatNode node.
	VisitSplatNode(node *SplatNode)

	// VisitStatementsNode visits a StatementsNode node.
	VisitStatementsNode(node *StatementsNode)

	// VisitStringNode visits a StringNode node.
	VisitStringNode(node *StringNode)

	// VisitSuperNode visits a SuperNode node.
	VisitSuperNode(node *SuperNode)

	// VisitSymbolNode visits a SymbolNode node.
	VisitSymbolNode(node *SymbolNode)

	// VisitTrueNode visits a TrueNode node.
	VisitTrueNode(node *TrueNode)

	// VisitUndefNode visits a UndefNode node.
	VisitUndefNode(node *UndefNode)

	// VisitUnlessNode visits a UnlessNode node.
	VisitUnlessNode(node *UnlessNode)

	// VisitUntilNode visits a UntilNode node.
	VisitUntilNode(node *UntilNode)

	// VisitWhenNode visits a WhenNode node.
	VisitWhenNode(node *WhenNode)

	// VisitWhileNode visits a WhileNode node.
	VisitWhileNode(node *WhileNode)

	// VisitXStringNode visits a XStringNode node.
	VisitXStringNode(node *XStringNode)

	// VisitYieldNode visits a YieldNode node.
	VisitYieldNode(node *YieldNode)
}

// DefaultVisitor provides a default implementation of the Visitor interface
// that simply continues walking the tree by visiting child nodes.
type DefaultVisitor struct{}

// Visit calls Accept on the given node if it is not nil.
func (v *DefaultVisitor) Visit(node Node) {
	if node != nil {
		node.Accept(v)
	}
}

// VisitAll visits each node in the slice by calling Accept on each one.
func (v *DefaultVisitor) VisitAll(nodes []Node) {
	for _, node := range nodes {
		if node != nil {
			node.Accept(v)
		}
	}
}

// VisitChildNodes visits the child nodes of the given node by calling Accept on each one.
func (v *DefaultVisitor) VisitChildNodes(node Node) {
	for _, childNode := range node.CompactChildNodes() {
		childNode.Accept(v)
	}
}

// VisitAliasGlobalVariableNode visits a AliasGlobalVariableNode node.
func (v *DefaultVisitor) VisitAliasGlobalVariableNode(node *AliasGlobalVariableNode) {
	v.VisitChildNodes(node)
}

// VisitAliasMethodNode visits a AliasMethodNode node.
func (v *DefaultVisitor) VisitAliasMethodNode(node *AliasMethodNode) {
	v.VisitChildNodes(node)
}

// VisitAlternationPatternNode visits a AlternationPatternNode node.
func (v *DefaultVisitor) VisitAlternationPatternNode(node *AlternationPatternNode) {
	v.VisitChildNodes(node)
}

// VisitAndNode visits a AndNode node.
func (v *DefaultVisitor) VisitAndNode(node *AndNode) {
	v.VisitChildNodes(node)
}

// VisitArgumentsNode visits a ArgumentsNode node.
func (v *DefaultVisitor) VisitArgumentsNode(node *ArgumentsNode) {
	v.VisitChildNodes(node)
}

// VisitArrayNode visits a ArrayNode node.
func (v *DefaultVisitor) VisitArrayNode(node *ArrayNode) {
	v.VisitChildNodes(node)
}

// VisitArrayPatternNode visits a ArrayPatternNode node.
func (v *DefaultVisitor) VisitArrayPatternNode(node *ArrayPatternNode) {
	v.VisitChildNodes(node)
}

// VisitAssocNode visits a AssocNode node.
func (v *DefaultVisitor) VisitAssocNode(node *AssocNode) {
	v.VisitChildNodes(node)
}

// VisitAssocSplatNode visits a AssocSplatNode node.
func (v *DefaultVisitor) VisitAssocSplatNode(node *AssocSplatNode) {
	v.VisitChildNodes(node)
}

// VisitBackReferenceReadNode visits a BackReferenceReadNode node.
func (v *DefaultVisitor) VisitBackReferenceReadNode(node *BackReferenceReadNode) {
	v.VisitChildNodes(node)
}

// VisitBeginNode visits a BeginNode node.
func (v *DefaultVisitor) VisitBeginNode(node *BeginNode) {
	v.VisitChildNodes(node)
}

// VisitBlockArgumentNode visits a BlockArgumentNode node.
func (v *DefaultVisitor) VisitBlockArgumentNode(node *BlockArgumentNode) {
	v.VisitChildNodes(node)
}

// VisitBlockLocalVariableNode visits a BlockLocalVariableNode node.
func (v *DefaultVisitor) VisitBlockLocalVariableNode(node *BlockLocalVariableNode) {
	v.VisitChildNodes(node)
}

// VisitBlockNode visits a BlockNode node.
func (v *DefaultVisitor) VisitBlockNode(node *BlockNode) {
	v.VisitChildNodes(node)
}

// VisitBlockParameterNode visits a BlockParameterNode node.
func (v *DefaultVisitor) VisitBlockParameterNode(node *BlockParameterNode) {
	v.VisitChildNodes(node)
}

// VisitBlockParametersNode visits a BlockParametersNode node.
func (v *DefaultVisitor) VisitBlockParametersNode(node *BlockParametersNode) {
	v.VisitChildNodes(node)
}

// VisitBreakNode visits a BreakNode node.
func (v *DefaultVisitor) VisitBreakNode(node *BreakNode) {
	v.VisitChildNodes(node)
}

// VisitCallAndWriteNode visits a CallAndWriteNode node.
func (v *DefaultVisitor) VisitCallAndWriteNode(node *CallAndWriteNode) {
	v.VisitChildNodes(node)
}

// VisitCallNode visits a CallNode node.
func (v *DefaultVisitor) VisitCallNode(node *CallNode) {
	v.VisitChildNodes(node)
}

// VisitCallOperatorWriteNode visits a CallOperatorWriteNode node.
func (v *DefaultVisitor) VisitCallOperatorWriteNode(node *CallOperatorWriteNode) {
	v.VisitChildNodes(node)
}

// VisitCallOrWriteNode visits a CallOrWriteNode node.
func (v *DefaultVisitor) VisitCallOrWriteNode(node *CallOrWriteNode) {
	v.VisitChildNodes(node)
}

// VisitCallTargetNode visits a CallTargetNode node.
func (v *DefaultVisitor) VisitCallTargetNode(node *CallTargetNode) {
	v.VisitChildNodes(node)
}

// VisitCapturePatternNode visits a CapturePatternNode node.
func (v *DefaultVisitor) VisitCapturePatternNode(node *CapturePatternNode) {
	v.VisitChildNodes(node)
}

// VisitCaseMatchNode visits a CaseMatchNode node.
func (v *DefaultVisitor) VisitCaseMatchNode(node *CaseMatchNode) {
	v.VisitChildNodes(node)
}

// VisitCaseNode visits a CaseNode node.
func (v *DefaultVisitor) VisitCaseNode(node *CaseNode) {
	v.VisitChildNodes(node)
}

// VisitClassNode visits a ClassNode node.
func (v *DefaultVisitor) VisitClassNode(node *ClassNode) {
	v.VisitChildNodes(node)
}

// VisitClassVariableAndWriteNode visits a ClassVariableAndWriteNode node.
func (v *DefaultVisitor) VisitClassVariableAndWriteNode(node *ClassVariableAndWriteNode) {
	v.VisitChildNodes(node)
}

// VisitClassVariableOperatorWriteNode visits a ClassVariableOperatorWriteNode node.
func (v *DefaultVisitor) VisitClassVariableOperatorWriteNode(node *ClassVariableOperatorWriteNode) {
	v.VisitChildNodes(node)
}

// VisitClassVariableOrWriteNode visits a ClassVariableOrWriteNode node.
func (v *DefaultVisitor) VisitClassVariableOrWriteNode(node *ClassVariableOrWriteNode) {
	v.VisitChildNodes(node)
}

// VisitClassVariableReadNode visits a ClassVariableReadNode node.
func (v *DefaultVisitor) VisitClassVariableReadNode(node *ClassVariableReadNode) {
	v.VisitChildNodes(node)
}

// VisitClassVariableTargetNode visits a ClassVariableTargetNode node.
func (v *DefaultVisitor) VisitClassVariableTargetNode(node *ClassVariableTargetNode) {
	v.VisitChildNodes(node)
}

// VisitClassVariableWriteNode visits a ClassVariableWriteNode node.
func (v *DefaultVisitor) VisitClassVariableWriteNode(node *ClassVariableWriteNode) {
	v.VisitChildNodes(node)
}

// VisitConstantAndWriteNode visits a ConstantAndWriteNode node.
func (v *DefaultVisitor) VisitConstantAndWriteNode(node *ConstantAndWriteNode) {
	v.VisitChildNodes(node)
}

// VisitConstantOperatorWriteNode visits a ConstantOperatorWriteNode node.
func (v *DefaultVisitor) VisitConstantOperatorWriteNode(node *ConstantOperatorWriteNode) {
	v.VisitChildNodes(node)
}

// VisitConstantOrWriteNode visits a ConstantOrWriteNode node.
func (v *DefaultVisitor) VisitConstantOrWriteNode(node *ConstantOrWriteNode) {
	v.VisitChildNodes(node)
}

// VisitConstantPathAndWriteNode visits a ConstantPathAndWriteNode node.
func (v *DefaultVisitor) VisitConstantPathAndWriteNode(node *ConstantPathAndWriteNode) {
	v.VisitChildNodes(node)
}

// VisitConstantPathNode visits a ConstantPathNode node.
func (v *DefaultVisitor) VisitConstantPathNode(node *ConstantPathNode) {
	v.VisitChildNodes(node)
}

// VisitConstantPathOperatorWriteNode visits a ConstantPathOperatorWriteNode node.
func (v *DefaultVisitor) VisitConstantPathOperatorWriteNode(node *ConstantPathOperatorWriteNode) {
	v.VisitChildNodes(node)
}

// VisitConstantPathOrWriteNode visits a ConstantPathOrWriteNode node.
func (v *DefaultVisitor) VisitConstantPathOrWriteNode(node *ConstantPathOrWriteNode) {
	v.VisitChildNodes(node)
}

// VisitConstantPathTargetNode visits a ConstantPathTargetNode node.
func (v *DefaultVisitor) VisitConstantPathTargetNode(node *ConstantPathTargetNode) {
	v.VisitChildNodes(node)
}

// VisitConstantPathWriteNode visits a ConstantPathWriteNode node.
func (v *DefaultVisitor) VisitConstantPathWriteNode(node *ConstantPathWriteNode) {
	v.VisitChildNodes(node)
}

// VisitConstantReadNode visits a ConstantReadNode node.
func (v *DefaultVisitor) VisitConstantReadNode(node *ConstantReadNode) {
	v.VisitChildNodes(node)
}

// VisitConstantTargetNode visits a ConstantTargetNode node.
func (v *DefaultVisitor) VisitConstantTargetNode(node *ConstantTargetNode) {
	v.VisitChildNodes(node)
}

// VisitConstantWriteNode visits a ConstantWriteNode node.
func (v *DefaultVisitor) VisitConstantWriteNode(node *ConstantWriteNode) {
	v.VisitChildNodes(node)
}

// VisitDefNode visits a DefNode node.
func (v *DefaultVisitor) VisitDefNode(node *DefNode) {
	v.VisitChildNodes(node)
}

// VisitDefinedNode visits a DefinedNode node.
func (v *DefaultVisitor) VisitDefinedNode(node *DefinedNode) {
	v.VisitChildNodes(node)
}

// VisitElseNode visits a ElseNode node.
func (v *DefaultVisitor) VisitElseNode(node *ElseNode) {
	v.VisitChildNodes(node)
}

// VisitEmbeddedStatementsNode visits a EmbeddedStatementsNode node.
func (v *DefaultVisitor) VisitEmbeddedStatementsNode(node *EmbeddedStatementsNode) {
	v.VisitChildNodes(node)
}

// VisitEmbeddedVariableNode visits a EmbeddedVariableNode node.
func (v *DefaultVisitor) VisitEmbeddedVariableNode(node *EmbeddedVariableNode) {
	v.VisitChildNodes(node)
}

// VisitEnsureNode visits a EnsureNode node.
func (v *DefaultVisitor) VisitEnsureNode(node *EnsureNode) {
	v.VisitChildNodes(node)
}

// VisitFalseNode visits a FalseNode node.
func (v *DefaultVisitor) VisitFalseNode(node *FalseNode) {
	v.VisitChildNodes(node)
}

// VisitFindPatternNode visits a FindPatternNode node.
func (v *DefaultVisitor) VisitFindPatternNode(node *FindPatternNode) {
	v.VisitChildNodes(node)
}

// VisitFlipFlopNode visits a FlipFlopNode node.
func (v *DefaultVisitor) VisitFlipFlopNode(node *FlipFlopNode) {
	v.VisitChildNodes(node)
}

// VisitFloatNode visits a FloatNode node.
func (v *DefaultVisitor) VisitFloatNode(node *FloatNode) {
	v.VisitChildNodes(node)
}

// VisitForNode visits a ForNode node.
func (v *DefaultVisitor) VisitForNode(node *ForNode) {
	v.VisitChildNodes(node)
}

// VisitForwardingArgumentsNode visits a ForwardingArgumentsNode node.
func (v *DefaultVisitor) VisitForwardingArgumentsNode(node *ForwardingArgumentsNode) {
	v.VisitChildNodes(node)
}

// VisitForwardingParameterNode visits a ForwardingParameterNode node.
func (v *DefaultVisitor) VisitForwardingParameterNode(node *ForwardingParameterNode) {
	v.VisitChildNodes(node)
}

// VisitForwardingSuperNode visits a ForwardingSuperNode node.
func (v *DefaultVisitor) VisitForwardingSuperNode(node *ForwardingSuperNode) {
	v.VisitChildNodes(node)
}

// VisitGlobalVariableAndWriteNode visits a GlobalVariableAndWriteNode node.
func (v *DefaultVisitor) VisitGlobalVariableAndWriteNode(node *GlobalVariableAndWriteNode) {
	v.VisitChildNodes(node)
}

// VisitGlobalVariableOperatorWriteNode visits a GlobalVariableOperatorWriteNode node.
func (v *DefaultVisitor) VisitGlobalVariableOperatorWriteNode(node *GlobalVariableOperatorWriteNode) {
	v.VisitChildNodes(node)
}

// VisitGlobalVariableOrWriteNode visits a GlobalVariableOrWriteNode node.
func (v *DefaultVisitor) VisitGlobalVariableOrWriteNode(node *GlobalVariableOrWriteNode) {
	v.VisitChildNodes(node)
}

// VisitGlobalVariableReadNode visits a GlobalVariableReadNode node.
func (v *DefaultVisitor) VisitGlobalVariableReadNode(node *GlobalVariableReadNode) {
	v.VisitChildNodes(node)
}

// VisitGlobalVariableTargetNode visits a GlobalVariableTargetNode node.
func (v *DefaultVisitor) VisitGlobalVariableTargetNode(node *GlobalVariableTargetNode) {
	v.VisitChildNodes(node)
}

// VisitGlobalVariableWriteNode visits a GlobalVariableWriteNode node.
func (v *DefaultVisitor) VisitGlobalVariableWriteNode(node *GlobalVariableWriteNode) {
	v.VisitChildNodes(node)
}

// VisitHashNode visits a HashNode node.
func (v *DefaultVisitor) VisitHashNode(node *HashNode) {
	v.VisitChildNodes(node)
}

// VisitHashPatternNode visits a HashPatternNode node.
func (v *DefaultVisitor) VisitHashPatternNode(node *HashPatternNode) {
	v.VisitChildNodes(node)
}

// VisitIfNode visits a IfNode node.
func (v *DefaultVisitor) VisitIfNode(node *IfNode) {
	v.VisitChildNodes(node)
}

// VisitImaginaryNode visits a ImaginaryNode node.
func (v *DefaultVisitor) VisitImaginaryNode(node *ImaginaryNode) {
	v.VisitChildNodes(node)
}

// VisitImplicitNode visits a ImplicitNode node.
func (v *DefaultVisitor) VisitImplicitNode(node *ImplicitNode) {
	v.VisitChildNodes(node)
}

// VisitImplicitRestNode visits a ImplicitRestNode node.
func (v *DefaultVisitor) VisitImplicitRestNode(node *ImplicitRestNode) {
	v.VisitChildNodes(node)
}

// VisitInNode visits a InNode node.
func (v *DefaultVisitor) VisitInNode(node *InNode) {
	v.VisitChildNodes(node)
}

// VisitIndexAndWriteNode visits a IndexAndWriteNode node.
func (v *DefaultVisitor) VisitIndexAndWriteNode(node *IndexAndWriteNode) {
	v.VisitChildNodes(node)
}

// VisitIndexOperatorWriteNode visits a IndexOperatorWriteNode node.
func (v *DefaultVisitor) VisitIndexOperatorWriteNode(node *IndexOperatorWriteNode) {
	v.VisitChildNodes(node)
}

// VisitIndexOrWriteNode visits a IndexOrWriteNode node.
func (v *DefaultVisitor) VisitIndexOrWriteNode(node *IndexOrWriteNode) {
	v.VisitChildNodes(node)
}

// VisitIndexTargetNode visits a IndexTargetNode node.
func (v *DefaultVisitor) VisitIndexTargetNode(node *IndexTargetNode) {
	v.VisitChildNodes(node)
}

// VisitInstanceVariableAndWriteNode visits a InstanceVariableAndWriteNode node.
func (v *DefaultVisitor) VisitInstanceVariableAndWriteNode(node *InstanceVariableAndWriteNode) {
	v.VisitChildNodes(node)
}

// VisitInstanceVariableOperatorWriteNode visits a InstanceVariableOperatorWriteNode node.
func (v *DefaultVisitor) VisitInstanceVariableOperatorWriteNode(node *InstanceVariableOperatorWriteNode) {
	v.VisitChildNodes(node)
}

// VisitInstanceVariableOrWriteNode visits a InstanceVariableOrWriteNode node.
func (v *DefaultVisitor) VisitInstanceVariableOrWriteNode(node *InstanceVariableOrWriteNode) {
	v.VisitChildNodes(node)
}

// VisitInstanceVariableReadNode visits a InstanceVariableReadNode node.
func (v *DefaultVisitor) VisitInstanceVariableReadNode(node *InstanceVariableReadNode) {
	v.VisitChildNodes(node)
}

// VisitInstanceVariableTargetNode visits a InstanceVariableTargetNode node.
func (v *DefaultVisitor) VisitInstanceVariableTargetNode(node *InstanceVariableTargetNode) {
	v.VisitChildNodes(node)
}

// VisitInstanceVariableWriteNode visits a InstanceVariableWriteNode node.
func (v *DefaultVisitor) VisitInstanceVariableWriteNode(node *InstanceVariableWriteNode) {
	v.VisitChildNodes(node)
}

// VisitIntegerNode visits a IntegerNode node.
func (v *DefaultVisitor) VisitIntegerNode(node *IntegerNode) {
	v.VisitChildNodes(node)
}

// VisitInterpolatedMatchLastLineNode visits a InterpolatedMatchLastLineNode node.
func (v *DefaultVisitor) VisitInterpolatedMatchLastLineNode(node *InterpolatedMatchLastLineNode) {
	v.VisitChildNodes(node)
}

// VisitInterpolatedRegularExpressionNode visits a InterpolatedRegularExpressionNode node.
func (v *DefaultVisitor) VisitInterpolatedRegularExpressionNode(node *InterpolatedRegularExpressionNode) {
	v.VisitChildNodes(node)
}

// VisitInterpolatedStringNode visits a InterpolatedStringNode node.
func (v *DefaultVisitor) VisitInterpolatedStringNode(node *InterpolatedStringNode) {
	v.VisitChildNodes(node)
}

// VisitInterpolatedSymbolNode visits a InterpolatedSymbolNode node.
func (v *DefaultVisitor) VisitInterpolatedSymbolNode(node *InterpolatedSymbolNode) {
	v.VisitChildNodes(node)
}

// VisitInterpolatedXStringNode visits a InterpolatedXStringNode node.
func (v *DefaultVisitor) VisitInterpolatedXStringNode(node *InterpolatedXStringNode) {
	v.VisitChildNodes(node)
}

// VisitItLocalVariableReadNode visits a ItLocalVariableReadNode node.
func (v *DefaultVisitor) VisitItLocalVariableReadNode(node *ItLocalVariableReadNode) {
	v.VisitChildNodes(node)
}

// VisitItParametersNode visits a ItParametersNode node.
func (v *DefaultVisitor) VisitItParametersNode(node *ItParametersNode) {
	v.VisitChildNodes(node)
}

// VisitKeywordHashNode visits a KeywordHashNode node.
func (v *DefaultVisitor) VisitKeywordHashNode(node *KeywordHashNode) {
	v.VisitChildNodes(node)
}

// VisitKeywordRestParameterNode visits a KeywordRestParameterNode node.
func (v *DefaultVisitor) VisitKeywordRestParameterNode(node *KeywordRestParameterNode) {
	v.VisitChildNodes(node)
}

// VisitLambdaNode visits a LambdaNode node.
func (v *DefaultVisitor) VisitLambdaNode(node *LambdaNode) {
	v.VisitChildNodes(node)
}

// VisitLocalVariableAndWriteNode visits a LocalVariableAndWriteNode node.
func (v *DefaultVisitor) VisitLocalVariableAndWriteNode(node *LocalVariableAndWriteNode) {
	v.VisitChildNodes(node)
}

// VisitLocalVariableOperatorWriteNode visits a LocalVariableOperatorWriteNode node.
func (v *DefaultVisitor) VisitLocalVariableOperatorWriteNode(node *LocalVariableOperatorWriteNode) {
	v.VisitChildNodes(node)
}

// VisitLocalVariableOrWriteNode visits a LocalVariableOrWriteNode node.
func (v *DefaultVisitor) VisitLocalVariableOrWriteNode(node *LocalVariableOrWriteNode) {
	v.VisitChildNodes(node)
}

// VisitLocalVariableReadNode visits a LocalVariableReadNode node.
func (v *DefaultVisitor) VisitLocalVariableReadNode(node *LocalVariableReadNode) {
	v.VisitChildNodes(node)
}

// VisitLocalVariableTargetNode visits a LocalVariableTargetNode node.
func (v *DefaultVisitor) VisitLocalVariableTargetNode(node *LocalVariableTargetNode) {
	v.VisitChildNodes(node)
}

// VisitLocalVariableWriteNode visits a LocalVariableWriteNode node.
func (v *DefaultVisitor) VisitLocalVariableWriteNode(node *LocalVariableWriteNode) {
	v.VisitChildNodes(node)
}

// VisitMatchLastLineNode visits a MatchLastLineNode node.
func (v *DefaultVisitor) VisitMatchLastLineNode(node *MatchLastLineNode) {
	v.VisitChildNodes(node)
}

// VisitMatchPredicateNode visits a MatchPredicateNode node.
func (v *DefaultVisitor) VisitMatchPredicateNode(node *MatchPredicateNode) {
	v.VisitChildNodes(node)
}

// VisitMatchRequiredNode visits a MatchRequiredNode node.
func (v *DefaultVisitor) VisitMatchRequiredNode(node *MatchRequiredNode) {
	v.VisitChildNodes(node)
}

// VisitMatchWriteNode visits a MatchWriteNode node.
func (v *DefaultVisitor) VisitMatchWriteNode(node *MatchWriteNode) {
	v.VisitChildNodes(node)
}

// VisitMissingNode visits a MissingNode node.
func (v *DefaultVisitor) VisitMissingNode(node *MissingNode) {
	v.VisitChildNodes(node)
}

// VisitModuleNode visits a ModuleNode node.
func (v *DefaultVisitor) VisitModuleNode(node *ModuleNode) {
	v.VisitChildNodes(node)
}

// VisitMultiTargetNode visits a MultiTargetNode node.
func (v *DefaultVisitor) VisitMultiTargetNode(node *MultiTargetNode) {
	v.VisitChildNodes(node)
}

// VisitMultiWriteNode visits a MultiWriteNode node.
func (v *DefaultVisitor) VisitMultiWriteNode(node *MultiWriteNode) {
	v.VisitChildNodes(node)
}

// VisitNextNode visits a NextNode node.
func (v *DefaultVisitor) VisitNextNode(node *NextNode) {
	v.VisitChildNodes(node)
}

// VisitNilNode visits a NilNode node.
func (v *DefaultVisitor) VisitNilNode(node *NilNode) {
	v.VisitChildNodes(node)
}

// VisitNoKeywordsParameterNode visits a NoKeywordsParameterNode node.
func (v *DefaultVisitor) VisitNoKeywordsParameterNode(node *NoKeywordsParameterNode) {
	v.VisitChildNodes(node)
}

// VisitNumberedParametersNode visits a NumberedParametersNode node.
func (v *DefaultVisitor) VisitNumberedParametersNode(node *NumberedParametersNode) {
	v.VisitChildNodes(node)
}

// VisitNumberedReferenceReadNode visits a NumberedReferenceReadNode node.
func (v *DefaultVisitor) VisitNumberedReferenceReadNode(node *NumberedReferenceReadNode) {
	v.VisitChildNodes(node)
}

// VisitOptionalKeywordParameterNode visits a OptionalKeywordParameterNode node.
func (v *DefaultVisitor) VisitOptionalKeywordParameterNode(node *OptionalKeywordParameterNode) {
	v.VisitChildNodes(node)
}

// VisitOptionalParameterNode visits a OptionalParameterNode node.
func (v *DefaultVisitor) VisitOptionalParameterNode(node *OptionalParameterNode) {
	v.VisitChildNodes(node)
}

// VisitOrNode visits a OrNode node.
func (v *DefaultVisitor) VisitOrNode(node *OrNode) {
	v.VisitChildNodes(node)
}

// VisitParametersNode visits a ParametersNode node.
func (v *DefaultVisitor) VisitParametersNode(node *ParametersNode) {
	v.VisitChildNodes(node)
}

// VisitParenthesesNode visits a ParenthesesNode node.
func (v *DefaultVisitor) VisitParenthesesNode(node *ParenthesesNode) {
	v.VisitChildNodes(node)
}

// VisitPinnedExpressionNode visits a PinnedExpressionNode node.
func (v *DefaultVisitor) VisitPinnedExpressionNode(node *PinnedExpressionNode) {
	v.VisitChildNodes(node)
}

// VisitPinnedVariableNode visits a PinnedVariableNode node.
func (v *DefaultVisitor) VisitPinnedVariableNode(node *PinnedVariableNode) {
	v.VisitChildNodes(node)
}

// VisitPostExecutionNode visits a PostExecutionNode node.
func (v *DefaultVisitor) VisitPostExecutionNode(node *PostExecutionNode) {
	v.VisitChildNodes(node)
}

// VisitPreExecutionNode visits a PreExecutionNode node.
func (v *DefaultVisitor) VisitPreExecutionNode(node *PreExecutionNode) {
	v.VisitChildNodes(node)
}

// VisitProgramNode visits a ProgramNode node.
func (v *DefaultVisitor) VisitProgramNode(node *ProgramNode) {
	v.VisitChildNodes(node)
}

// VisitRangeNode visits a RangeNode node.
func (v *DefaultVisitor) VisitRangeNode(node *RangeNode) {
	v.VisitChildNodes(node)
}

// VisitRationalNode visits a RationalNode node.
func (v *DefaultVisitor) VisitRationalNode(node *RationalNode) {
	v.VisitChildNodes(node)
}

// VisitRedoNode visits a RedoNode node.
func (v *DefaultVisitor) VisitRedoNode(node *RedoNode) {
	v.VisitChildNodes(node)
}

// VisitRegularExpressionNode visits a RegularExpressionNode node.
func (v *DefaultVisitor) VisitRegularExpressionNode(node *RegularExpressionNode) {
	v.VisitChildNodes(node)
}

// VisitRequiredKeywordParameterNode visits a RequiredKeywordParameterNode node.
func (v *DefaultVisitor) VisitRequiredKeywordParameterNode(node *RequiredKeywordParameterNode) {
	v.VisitChildNodes(node)
}

// VisitRequiredParameterNode visits a RequiredParameterNode node.
func (v *DefaultVisitor) VisitRequiredParameterNode(node *RequiredParameterNode) {
	v.VisitChildNodes(node)
}

// VisitRescueModifierNode visits a RescueModifierNode node.
func (v *DefaultVisitor) VisitRescueModifierNode(node *RescueModifierNode) {
	v.VisitChildNodes(node)
}

// VisitRescueNode visits a RescueNode node.
func (v *DefaultVisitor) VisitRescueNode(node *RescueNode) {
	v.VisitChildNodes(node)
}

// VisitRestParameterNode visits a RestParameterNode node.
func (v *DefaultVisitor) VisitRestParameterNode(node *RestParameterNode) {
	v.VisitChildNodes(node)
}

// VisitRetryNode visits a RetryNode node.
func (v *DefaultVisitor) VisitRetryNode(node *RetryNode) {
	v.VisitChildNodes(node)
}

// VisitReturnNode visits a ReturnNode node.
func (v *DefaultVisitor) VisitReturnNode(node *ReturnNode) {
	v.VisitChildNodes(node)
}

// VisitSelfNode visits a SelfNode node.
func (v *DefaultVisitor) VisitSelfNode(node *SelfNode) {
	v.VisitChildNodes(node)
}

// VisitShareableConstantNode visits a ShareableConstantNode node.
func (v *DefaultVisitor) VisitShareableConstantNode(node *ShareableConstantNode) {
	v.VisitChildNodes(node)
}

// VisitSingletonClassNode visits a SingletonClassNode node.
func (v *DefaultVisitor) VisitSingletonClassNode(node *SingletonClassNode) {
	v.VisitChildNodes(node)
}

// VisitSourceEncodingNode visits a SourceEncodingNode node.
func (v *DefaultVisitor) VisitSourceEncodingNode(node *SourceEncodingNode) {
	v.VisitChildNodes(node)
}

// VisitSourceFileNode visits a SourceFileNode node.
func (v *DefaultVisitor) VisitSourceFileNode(node *SourceFileNode) {
	v.VisitChildNodes(node)
}

// VisitSourceLineNode visits a SourceLineNode node.
func (v *DefaultVisitor) VisitSourceLineNode(node *SourceLineNode) {
	v.VisitChildNodes(node)
}

// VisitSplatNode visits a SplatNode node.
func (v *DefaultVisitor) VisitSplatNode(node *SplatNode) {
	v.VisitChildNodes(node)
}

// VisitStatementsNode visits a StatementsNode node.
func (v *DefaultVisitor) VisitStatementsNode(node *StatementsNode) {
	v.VisitChildNodes(node)
}

// VisitStringNode visits a StringNode node.
func (v *DefaultVisitor) VisitStringNode(node *StringNode) {
	v.VisitChildNodes(node)
}

// VisitSuperNode visits a SuperNode node.
func (v *DefaultVisitor) VisitSuperNode(node *SuperNode) {
	v.VisitChildNodes(node)
}

// VisitSymbolNode visits a SymbolNode node.
func (v *DefaultVisitor) VisitSymbolNode(node *SymbolNode) {
	v.VisitChildNodes(node)
}

// VisitTrueNode visits a TrueNode node.
func (v *DefaultVisitor) VisitTrueNode(node *TrueNode) {
	v.VisitChildNodes(node)
}

// VisitUndefNode visits a UndefNode node.
func (v *DefaultVisitor) VisitUndefNode(node *UndefNode) {
	v.VisitChildNodes(node)
}

// VisitUnlessNode visits a UnlessNode node.
func (v *DefaultVisitor) VisitUnlessNode(node *UnlessNode) {
	v.VisitChildNodes(node)
}

// VisitUntilNode visits a UntilNode node.
func (v *DefaultVisitor) VisitUntilNode(node *UntilNode) {
	v.VisitChildNodes(node)
}

// VisitWhenNode visits a WhenNode node.
func (v *DefaultVisitor) VisitWhenNode(node *WhenNode) {
	v.VisitChildNodes(node)
}

// VisitWhileNode visits a WhileNode node.
func (v *DefaultVisitor) VisitWhileNode(node *WhileNode) {
	v.VisitChildNodes(node)
}

// VisitXStringNode visits a XStringNode node.
func (v *DefaultVisitor) VisitXStringNode(node *XStringNode) {
	v.VisitChildNodes(node)
}

// VisitYieldNode visits a YieldNode node.
func (v *DefaultVisitor) VisitYieldNode(node *YieldNode) {
	v.VisitChildNodes(node)
}
