package generator

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

//go:embed templates/*.tmpl
var templates embed.FS

// LegacyBanner controls whether the generated files carry the banner emitted
// by prism's Ruby pipeline. It exists so the port can be verified against the
// previously committed files byte for byte; the banner text is updated once
// that check has passed.
var LegacyBanner = true

// banner reproduces the header that prism's template.rb writes above every
// generated file. The referenced path is padded to 74 columns so the comment
// block stays aligned.
func banner(templatePath string) string {
	var script, path string

	if LegacyBanner {
		script = "templates/template.rb"
		path = "templates/../../templates/" + templatePath + ".erb"
	} else {
		script = "internal/generator"
		path = "internal/generator/templates/" + templatePath + ".tmpl"
	}

	if len(path) < 74 {
		path += strings.Repeat(" ", 74-len(path))
	}

	return "/*----------------------------------------------------------------------------*/\n" +
		"/* This file is generated by the " + script + " script and should not  */\n" +
		"/* be modified manually. See                                                  */\n" +
		"/* " + path + " */\n" +
		"/* if you are looking to modify the                                           */\n" +
		"/* template                                                                   */\n" +
		"/*----------------------------------------------------------------------------*/\n\n"
}

// Render executes the named template against the config and returns the
// formatted Go source.
func Render(name string, config *Config) ([]byte, error) {
	tmpl, err := template.New(name).Funcs(funcs()).ParseFS(templates, "templates/"+name)
	if err != nil {
		return nil, fmt.Errorf("failed to parse template %s: %w", name, err)
	}

	var buf bytes.Buffer

	buf.WriteString(banner(strings.TrimSuffix(name, ".tmpl")))

	if err := tmpl.Execute(&buf, config); err != nil {
		return nil, fmt.Errorf("failed to execute template %s: %w", name, err)
	}

	return buf.Bytes(), nil
}

// Generate renders every template and writes the results into dir.
func Generate(configPath, dir string) error {
	config, err := Load(configPath)
	if err != nil {
		return err
	}

	outputs := map[string]string{
		"gen_nodes.go.tmpl":        "gen_nodes.go",
		"gen_visitor.go.tmpl":      "gen_visitor.go",
		"gen_deserialize.go.tmpl":  "gen_deserialize.go",
		"gen_nodes_test.go.tmpl":   "gen_nodes_test.go",
		"gen_visitor_test.go.tmpl": "gen_visitor_test.go",
	}

	for tmplName, outName := range outputs {
		rendered, err := Render(tmplName, config)
		if err != nil {
			return err
		}

		// gofmt the result so the committed files match what `go fmt`
		// would produce, the same way the previous pipeline ran go fmt
		// after generating.
		formatted, err := format.Source(rendered)
		if err != nil {
			// Write the unformatted output so the syntax error can be
			// inspected directly.
			path := filepath.Join(dir, outName+".broken")
			_ = os.WriteFile(path, rendered, 0o644)

			return fmt.Errorf("failed to format %s (unformatted output written to %s): %w", outName, path, err)
		}

		if err := os.WriteFile(filepath.Join(dir, outName), formatted, 0o644); err != nil {
			return fmt.Errorf("failed to write %s: %w", outName, err)
		}
	}

	return nil
}

func funcs() template.FuncMap {
	return template.FuncMap{
		"camelcase":    GoCamelCase,
		"commentLines": CommentLines,
		"flagBit":      func(index int) int { return index + CommonFlagsCount },
		"lower":        strings.ToLower,
		"inc":          func(i int) int { return i + 1 },
	}
}
