package generator

import (
	"bytes"
	"embed"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

//go:embed templates/*.tmpl
var templates embed.FS

// banner is the header written above every generated file. The first line
// follows the convention tools look for to recognise generated code.
func banner(templatePath string) string {
	return "// Code generated by internal/generator. DO NOT EDIT.\n" +
		"//\n" +
		"// Edit internal/generator/templates/" + templatePath + ".tmpl instead,\n" +
		"// then run: go generate ./...\n\n"
}

// Render executes the named template against the config and returns the
// formatted Go source.
func Render(name string, config *Config) ([]byte, error) {
	tmpl, err := template.New(name).Funcs(funcs()).ParseFS(templates, "templates/"+name)
	if err != nil {
		return nil, fmt.Errorf("failed to parse template %s: %w", name, err)
	}

	var buf bytes.Buffer

	buf.WriteString(banner(strings.TrimSuffix(name, ".tmpl")))

	if err := tmpl.Execute(&buf, config); err != nil {
		return nil, fmt.Errorf("failed to execute template %s: %w", name, err)
	}

	return buf.Bytes(), nil
}

// Generate renders every template and writes the results into dir. versionPath
// points at prism's include/prism/version.h, which supplies the version the
// deserializer checks against.
func Generate(configPath, versionPath, dir string) error {
	config, err := Load(configPath)
	if err != nil {
		return err
	}

	version, err := ReadVersion(versionPath)
	if err != nil {
		return err
	}

	config.Version = version

	outputs := map[string]string{
		"gen_nodes.go.tmpl":        "gen_nodes.go",
		"gen_visitor.go.tmpl":      "gen_visitor.go",
		"gen_deserialize.go.tmpl":  "gen_deserialize.go",
		"gen_nodes_test.go.tmpl":   "gen_nodes_test.go",
		"gen_visitor_test.go.tmpl": "gen_visitor_test.go",
	}

	for tmplName, outName := range outputs {
		rendered, err := Render(tmplName, config)
		if err != nil {
			return err
		}

		// gofmt the result so the committed files match what `go fmt`
		// would produce, the same way the previous pipeline ran go fmt
		// after generating.
		formatted, err := format.Source(rendered)
		if err != nil {
			// Write the unformatted output so the syntax error can be
			// inspected directly.
			path := filepath.Join(dir, outName+".broken")
			_ = os.WriteFile(path, rendered, 0o644)

			return fmt.Errorf("failed to format %s (unformatted output written to %s): %w", outName, path, err)
		}

		if err := os.WriteFile(filepath.Join(dir, outName), formatted, 0o644); err != nil {
			return fmt.Errorf("failed to write %s: %w", outName, err)
		}
	}

	return nil
}

func funcs() template.FuncMap {
	return template.FuncMap{
		"camelcase":    GoCamelCase,
		"commentLines": CommentLines,
		"flagBit":      func(index int) int { return index + CommonFlagsCount },
		"lower":        strings.ToLower,
		"inc":          func(i int) int { return i + 1 },
	}
}
